from __future__ import annotations

from copy import deepcopy


CHAPTERS = [
    {
        "id": "00",
        "number": "00",
        "title": "Tensors and Autograd",
        "lesson": "00_tensors_and_autograd",
        "summary": "Start from absolute basics: create tensors, inspect shapes, dtypes, slicing, simple reductions, NumPy relation, and then learn the backward/update loop that powers training.",
        "image": "00_gradient_descent.png",
        "script_path": "tutorials/00_tensors_and_autograd.py",
        "pdf_path": "tutorials/pdfs/00_tensors_and_autograd.pdf",
        "question_ids": ["q30_create_tensor_from_list", "q31_tensor_dtype", "q32_make_zeros_tensor", "q33_slice_first_row", "q34_tensor_num_dims", "q35_sum_columns", "q00_add_tensors", "q01_trainable_scalar", "q08_matrix_multiply", "q09_tensor_mean", "q10_gradient_step"],
        "previous_chapter": None,
        "next_chapter": "01",
        "sections": [
            {"type": "paragraph", "content": "PyTorch revolves around tensors and autograd. Tensors hold numbers in a structured way, and autograd tracks how a final loss depends on trainable values."},
            {"type": "paragraph", "content": "If you are brand new, start with three things: how to create a tensor, how to inspect its shape, and how to inspect its dtype. Those three ideas show up in almost every PyTorch program."},
            {"type": "list", "title": "What to understand first", "items": ["A scalar has shape (). A vector may have shape (3,). A matrix may have shape (2, 2).", "A dtype tells PyTorch what kind of numbers the tensor stores, such as integers or floating point values.", "Elementwise operations keep the same shape when the inputs match.", "Calling backward() computes gradients for tensors with requires_grad=True."]},
            {"type": "code", "title": "Creating basic tensors", "content": "x = torch.tensor([1.0, 2.0, 3.0])\nprint(x.shape)   # torch.Size([3])\nprint(x.dtype)   # torch.float32 by default for these values\ny = torch.zeros(2, 3)"},
            {"type": "paragraph", "content": "A tensor is just a container for numbers plus metadata. The metadata matters. Shape tells you how the values are arranged. Dtype tells you the numeric kind. Device tells you where the tensor lives, such as CPU or later MPS on your Mac."},
            {"type": "paragraph", "content": "If you already know NumPy arrays, PyTorch tensors will feel familiar. Both represent n-dimensional blocks of numbers and support indexing, slicing, reshaping, and vectorized math. The big extra thing in PyTorch is autograd and deep-learning layers."},
            {"type": "list", "title": "NumPy and PyTorch side by side", "items": ["NumPy uses `np.array(...)`; PyTorch uses `torch.tensor(...)`.", "NumPy is widely used for general numerical work.", "PyTorch tensors can participate in autograd when `requires_grad=True`.", "PyTorch models and optimizers are built around tensors, so tensors are the natural object for deep learning."]},
            {"type": "list", "title": "Common tensor constructors", "items": ["torch.tensor([...]) builds a tensor from Python values.", "torch.zeros(rows, cols) builds a tensor full of zeros.", "torch.ones(...) builds a tensor full of ones.", "torch.arange(start, end) builds a simple counting tensor."]},
            {"type": "paragraph", "content": "One useful beginner habit is to separate the ideas of data and operations. A tensor is the data. Operations like add, multiply, sum, reshape, and slice transform that data. Most PyTorch code is just a sequence of tensor operations applied in the right order."},
            {"type": "code", "title": "Inspecting tensor metadata", "content": "x = torch.tensor([[1, 2], [3, 4]], dtype=torch.float32)\nprint(x)\nprint(x.shape)   # torch.Size([2, 2])\nprint(x.dtype)   # torch.float32\nprint(x.ndim)    # 2 dimensions"},
            {"type": "paragraph", "content": "Dtype matters more than beginners expect. Integer tensors are fine for indexes or labels, but many training computations need floating point tensors because gradients and parameter updates involve decimal values. If a result looks strange, checking `x.dtype` is often worthwhile."},
            {"type": "code", "title": "Integer vs float tensors", "content": "ints = torch.tensor([1, 2, 3])\nprint(ints.dtype)  # often torch.int64\nfloats = torch.tensor([1, 2, 3], dtype=torch.float32)\nprint(floats.dtype)  # torch.float32"},
            {"type": "paragraph", "content": "Floating point tensors also come in different precisions. The most common one in PyTorch is `torch.float32`. You will also see `torch.float16` which is often called half precision or just half, and `torch.float64` which is often called double precision or just double."},
            {"type": "list", "title": "Common floating point dtypes", "items": ["`torch.float16` or half: uses less memory, lower precision.", "`torch.float32`: the default for most training and the most common choice.", "`torch.float64` or double: higher precision, more memory, often used in scientific or debugging contexts."]},
            {"type": "code", "title": "Half, float, and double", "content": "half_tensor = torch.tensor([1.0, 2.0], dtype=torch.float16)\nfloat_tensor = torch.tensor([1.0, 2.0], dtype=torch.float32)\ndouble_tensor = torch.tensor([1.0, 2.0], dtype=torch.float64)\n\nprint(half_tensor.dtype)    # torch.float16\nprint(float_tensor.dtype)   # torch.float32\nprint(double_tensor.dtype)  # torch.float64"},
            {"type": "paragraph", "content": "Higher precision means numbers can be represented more accurately, but it also costs more memory and usually more compute. Lower precision saves memory and can be faster on some hardware, but very small numeric differences may be lost. That tradeoff is why dtype matters in real training systems."},
            {"type": "paragraph", "content": "For a beginner learning on CPU, `torch.float32` is the best default. It is the standard choice in most beginner tutorials and examples. Half precision becomes more important later when people optimize large models on GPUs. Double precision is helpful when you want extra numerical accuracy, but it is not the usual default in deep learning."},
            {"type": "code", "title": "Changing dtype", "content": "x = torch.tensor([1, 2, 3])\nprint(x.dtype)\n\nx_float = x.float()      # convert to float32\nx_half = x.half()        # convert to float16\nx_double = x.double()    # convert to float64\n\nprint(x_float.dtype)\nprint(x_half.dtype)\nprint(x_double.dtype)"},
            {"type": "paragraph", "content": "The names `half()`, `float()`, and `double()` are just convenient conversions. They are shorthand for converting a tensor to `float16`, `float32`, and `float64`. You can also use `.to(dtype=...)` when you want a more general conversion style."},
            {"type": "code", "title": "Converting with .to()", "content": "x = torch.tensor([1, 2, 3])\nx = x.to(dtype=torch.float32)\nprint(x.dtype)"},
            {"type": "callout", "title": "Practical rule", "content": "If you are unsure, use `torch.float32`. That is the safest and most common dtype for beginner PyTorch code."},
            {"type": "callout", "title": "Why half is not the default here", "content": "Half precision can be useful for speed and memory savings, but it is easier to run into numerical issues and hardware-specific behavior. For learning fundamentals on CPU, it is usually more trouble than benefit."},
            {"type": "callout", "title": "Why double exists", "content": "Double precision keeps more numerical detail. It can help in some scientific calculations or debugging tiny numerical differences, but it is usually not necessary for standard beginner neural network training."},
            {"type": "paragraph", "content": "Slicing a tensor means selecting part of it with bracket notation. This is one of the most basic and most useful skills in numerical computing. You can take one row, one column, or a smaller block from a bigger tensor."},
            {"type": "code", "title": "Basic slicing examples", "content": "x = torch.tensor([[10, 20, 30], [40, 50, 60]])\nprint(x[0])      # first row -> tensor([10, 20, 30])\nprint(x[:, 1])   # second column -> tensor([20, 50])\nprint(x[0, 2])   # single value -> tensor(30)"},
            {"type": "paragraph", "content": "Indexing with a single integer removes that dimension from the result. That is why `x[0]` returns one row and has fewer dimensions than the original matrix. This behavior becomes important later when a model expects a batch dimension and you accidentally index it away."},
            {"type": "paragraph", "content": "A dimension is just an axis. For a matrix of shape `(2, 3)`, dimension 0 points across rows and dimension 1 points across columns. That is why summing with `dim=0` collapses rows and gives one value per column, while `dim=1` collapses columns and gives one value per row."},
            {"type": "code", "title": "Simple reduction operations", "content": "x = torch.tensor([[1.0, 2.0], [3.0, 4.0]])\nprint(x.sum())        # 10.0\nprint(x.sum(dim=0))   # tensor([4.0, 6.0])\nprint(x.sum(dim=1))   # tensor([3.0, 7.0])\nprint(x.mean())       # 2.5"},
            {"type": "list", "title": "Basic tensor operations worth memorizing", "items": ["`x.sum()` adds values.", "`x.mean()` averages values.", "`x.max()` returns the largest value.", "`x.min()` returns the smallest value.", "`x.ndim` tells you how many dimensions the tensor has."]},
            {"type": "paragraph", "content": "You can think of `sum`, `mean`, `max`, and `min` as reduction operations. They reduce many values down to fewer values. Reductions are common in machine learning because a model often produces many per-example numbers, and then a loss function reduces them to one scalar objective."},
            {"type": "paragraph", "content": "Autograd becomes important once a tensor represents something trainable, such as a weight. When `requires_grad=True`, PyTorch remembers the operations used to produce a result. After you call `backward()`, PyTorch fills `.grad` on the leaf tensors that need updates."},
            {"type": "paragraph", "content": "A useful mental model is that autograd builds a computation history while your code runs forward. Then `backward()` walks that history in reverse to compute gradients. You usually do not need to derive those gradients by hand, but you do need to know which tensors should track them."},
            {"type": "math", "title": "Symbolic Derivative Example", "content": "f(x) = x² + 2x + 10\nf′(x) = 2x + 2\n\nx = 3\nf′(3) = 2·3 + 2 = 8"},
            {"type": "code", "title": "Polynomial gradient example", "content": "x = torch.tensor(3.0, requires_grad=True)\nf = x**2 + 2*x + 10\nprint(f)           # 25.0\nprint(f.grad_fn)   # something like <AddBackward0 ...>\nf.backward()\nprint(x.grad)      # 8.0"},
            {"type": "paragraph", "content": "In that example, `grad_fn` means the current tensor was produced by some differentiable operation. PyTorch stores the local backward rule for each operation node. When you call `backward()`, PyTorch chains those local rules together using the chain rule from calculus."},
            {"type": "graph", "title": "How The Graph Looks Conceptually", "branches": [["x", "x²"], ["x", "2x"], ["10"]], "merge_label": "+", "result_chain": ["f"]},
            {"type": "math", "title": "Term-By-Term Derivative", "content": "d/dx (x² + 2x + 10)\n= d/dx (x²) + d/dx (2x) + d/dx (10)\n= 2x + 2 + 0\n= 2x + 2"},
            {"type": "paragraph", "content": "Now look at a chain-rule example. Let `z = tan(log(x^3 y^3 + xy + y^2 x))`. That expression looks intimidating, but the idea is still the same: break it into intermediate pieces and differentiate one step at a time."},
            {"type": "code", "title": "Breaking a complex expression into steps", "content": "a = x**3 * y**3\nb = x * y\nc = y**2 * x\nu = a + b + c\nv = log(u)\nz = tan(v)"},
            {"type": "paragraph", "content": "Once you define intermediates, the graph becomes easier to read. `z` depends on `v`. `v` depends on `u`. `u` depends on `a`, `b`, and `c`. And those depend on `x` and `y`. Autograd stores this graph automatically while your code runs forward."},
            {"type": "graph", "title": "Complex Graph Idea", "branches": [["x, y", "a = x³y³"], ["x, y", "b = xy"], ["x, y", "c = y²x"]], "merge_label": "sum", "result_chain": ["u", "log(u)", "tan(log(u)) = z"]},
            {"type": "math", "title": "Chain Rule Pieces", "content": "z = tan(v)\nv = log(u)\nu = x³y³ + xy + y²x\n\n∂z/∂v = sec²(v)\n∂v/∂u = 1/u\n\n∂u/∂x = 3x²y³ + y + y²\n∂u/∂y = 3x³y² + x + 2yx"},
            {"type": "math", "title": "Chain Rule Result", "content": "dz/dx = sec²(log(u)) · (1/u) · (3x²y³ + y + y²)\ndz/dy = sec²(log(u)) · (1/u) · (3x³y² + x + 2yx)\n\nu = x³y³ + xy + y²x"},
            {"type": "paragraph", "content": "That is exactly the style of work autograd is automating. It does not use magic. It applies the chain rule through the computation graph. Each node knows how to propagate gradients to its parents. PyTorch multiplies and accumulates those local gradient contributions for you."},
            {"type": "code", "title": "PyTorch version of the chain-rule example", "content": "x = torch.tensor(2.0, requires_grad=True)\ny = torch.tensor(1.5, requires_grad=True)\nz = torch.tan(torch.log(x**3 * y**3 + x*y + y**2 * x))\nprint(z.grad_fn)\nz.backward()\nprint(x.grad)\nprint(y.grad)"},
            {"type": "paragraph", "content": "A useful rule: leaf tensors are the original tensors you created directly, like `x` and `y`. Those are the tensors whose `.grad` fields PyTorch usually fills after `backward()`. Intermediate tensors like `u` or `v` usually have a `grad_fn`, but their `.grad` is not kept unless you explicitly ask for it."},
            {"type": "code", "title": "Leaf tensor idea", "content": "x = torch.tensor(2.0, requires_grad=True)\ny = x**2\nprint(x.grad_fn)  # None, because x is a leaf tensor\nprint(y.grad_fn)  # has a backward function because y came from an operation"},
            {"type": "code", "title": "Core update loop", "content": "loss.backward()\nwith torch.no_grad():\n    parameter -= learning_rate * parameter.grad\nparameter.grad.zero_()"},
            {"type": "list", "title": "Why each line in the update loop exists", "items": ["`loss.backward()` computes gradients.", "`torch.no_grad()` stops the update itself from being tracked.", "`parameter -= ...` changes the trainable value.", "`parameter.grad.zero_()` clears old gradients so the next step starts fresh."]},
            {"type": "code", "title": "Tiny autograd example", "content": "weight = torch.tensor(2.0, requires_grad=True)\nloss = (3 * weight - 9) ** 2\nloss.backward()\nprint(weight.grad)"},
            {"type": "paragraph", "content": "There is one more subtle point: gradients accumulate in `.grad`. If you call `backward()` twice without clearing `.grad`, PyTorch adds the new gradient on top of the old one. That is useful in some advanced cases, but in a normal training loop you usually want to zero the gradient before the next step."},
            {"type": "code", "title": "Why gradients are zeroed", "content": "x = torch.tensor(3.0, requires_grad=True)\ny = x**2\ny.backward()\nprint(x.grad)  # 6\n\ny = x**2\ny.backward()\nprint(x.grad)  # 12, because gradients accumulated"},
            {"type": "code", "title": "Worked example: from expression to gradient", "content": "x = torch.tensor(4.0, requires_grad=True)\ny = x**2 + 2*x + 10\n# Math says dy/dx = 2x + 2\n# At x = 4, gradient should be 10\ny.backward()\nprint(x.grad)  # 10"},
            {"type": "math", "title": "Math ↔ PyTorch Check", "content": "f(x) = x² + 2x + 10\nf′(x) = 2x + 2\n\nx = 4  ⇒  f′(4) = 10\nPyTorch: x.grad = 10"},
            {"type": "callout", "title": "Common mistakes with autograd", "content": "Forgetting `requires_grad=True`, calling `backward()` on something that is not a scalar without providing a gradient, updating parameters outside `torch.no_grad()`, and forgetting to clear `.grad` are the most common beginner mistakes."},
            {"type": "list", "title": "Recap checkpoint", "items": ["Can you explain what shape, dtype, and device mean?", "Can you create tensors with zeros, ones, and a specific dtype?", "Can you slice a row or a column from a matrix?", "Can you explain what `requires_grad`, `grad_fn`, and `.grad` each mean?", "Can you explain why gradients are zeroed between training steps?"]},
            {"type": "callout", "title": "What beginners usually mix up", "content": "A tensor value is not the same thing as its gradient. The tensor stores the current parameter or data. The gradient stores how the loss changes if that parameter changes a little."},
            {"type": "callout", "title": "How to think about grad_fn", "content": "`grad_fn` is PyTorch's reminder that this tensor came from a differentiable operation. It is not the final gradient value. It is the link back into the computation graph used during backpropagation."},
            {"type": "callout", "title": "How this chapter connects to the rest", "content": "Every later model in this course, from regression to CNNs and transformers, still runs on tensors. If tensor shapes and reductions are clear, later chapters become much easier to debug."},
            {"type": "callout", "title": "Beginner focus", "content": "Before worrying about neural networks, get comfortable creating tensors, reading shape and dtype, and understanding why only trainable parameters need requires_grad=True."},
        ],
    },
    {
        "id": "01",
        "number": "01",
        "title": "Shapes, Reshape, and Gradients",
        "lesson": "01_shapes_gradients_and_reshape",
        "summary": "Practice shape thinking so matrix multiplication, reshape, and broadcasting stop feeling mysterious.",
        "image": "01_matrix_multiplication.png",
        "script_path": "tutorials/01_shapes_gradients_and_reshape.py",
        "pdf_path": "tutorials/pdfs/01_shapes_gradients_and_reshape.pdf",
        "question_ids": ["q02_reshape_to_column", "q11_add_batch_dim", "q12_remove_singleton_dim", "q13_flatten_tensor", "q14_add_bias"],
        "previous_chapter": "00",
        "next_chapter": "02",
        "sections": [
            {"type": "paragraph", "content": "Most beginner PyTorch bugs are shape bugs. If you can read a shape and predict how it changes after reshape, unsqueeze, or matrix multiplication, later chapters become much easier."},
            {"type": "list", "title": "Shape rules to memorize", "items": ["reshape changes arrangement, not values.", "unsqueeze adds a dimension of size 1.", "broadcasting lets smaller tensors expand over compatible dimensions."]},
            {"type": "code", "title": "Common reshape pattern", "content": "x = torch.tensor([1, 2, 3])\ncolumn = x.unsqueeze(1)  # shape (3, 1)"},
            {"type": "paragraph", "content": "When you see a shape like `(3, 4)`, read it out loud as '3 rows and 4 columns'. When you see `(batch, features)`, think 'one row per example, one column per feature'. Naming the meaning of each dimension makes shape bugs easier to catch."},
            {"type": "list", "title": "Core shape operations", "items": ["`unsqueeze(dim)` adds a size-1 dimension.", "`squeeze(dim)` removes a size-1 dimension.", "`reshape(...)` changes the view of the same values into a new arrangement.", "`flatten()` turns many dimensions into one long dimension."]},
            {"type": "code", "title": "Three useful examples", "content": "x = torch.tensor([1, 2, 3])\nprint(x.shape)             # (3,)\nprint(x.unsqueeze(0).shape)  # (1, 3)\nprint(x.unsqueeze(1).shape)  # (3, 1)"},
            {"type": "paragraph", "content": "A lot of shape reasoning is really about preserving meaning. If a vector holds three features for one example, shape `(3,)` is ambiguous because it does not tell PyTorch whether that dimension should behave like a row or a column. Adding an explicit batch or feature dimension often removes that ambiguity."},
            {"type": "code", "title": "Row vs column intuition", "content": "x = torch.tensor([1.0, 2.0, 3.0])\nrow = x.unsqueeze(0)     # shape (1, 3)\ncolumn = x.unsqueeze(1)  # shape (3, 1)"},
            {"type": "paragraph", "content": "That distinction becomes critical for matrix multiplication. A row vector and a column vector contain the same values, but they interact with matrices differently. In linear algebra, shape is part of the meaning, not just a storage detail."},
            {"type": "code", "title": "Why row and column are different", "content": "row = torch.tensor([1.0, 2.0, 3.0]).unsqueeze(0)     # (1, 3)\ncolumn = torch.tensor([1.0, 2.0, 3.0]).unsqueeze(1)  # (3, 1)\nprint(row.shape)\nprint(column.shape)"},
            {"type": "paragraph", "content": "Broadcasting is the rule that allows PyTorch to combine different shapes when they are compatible. For example, adding a bias vector of shape `(3,)` to a matrix of shape `(2, 3)` works because PyTorch conceptually copies that bias across both rows."},
            {"type": "code", "title": "Broadcasting example", "content": "matrix = torch.tensor([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])\nbias = torch.tensor([10.0, 20.0, 30.0])\nresult = matrix + bias"},
            {"type": "paragraph", "content": "Broadcasting does not mean PyTorch literally copies the smaller tensor in memory first. The main idea is logical expansion: PyTorch behaves as if the smaller tensor were repeated across the compatible dimension so elementwise math can happen."},
            {"type": "paragraph", "content": "A clean way to check broadcasting is to compare dimensions from the rightmost side moving left. Two dimensions are compatible if they are equal or one of them is 1. If neither rule holds, broadcasting fails."},
            {"type": "code", "title": "Right-to-left broadcasting idea", "content": "(2, 3)\n(   3)\n# compare from the right:\n# 3 with 3 -> compatible\n# missing left dimension acts like 1 -> compatible"},
            {"type": "list", "title": "A practical shape checklist", "items": ["What does each dimension mean?", "Which dimensions should stay the same after this operation?", "Which dimension am I adding, removing, or collapsing?", "If broadcasting happens, along which axis is the smaller tensor expanding?"]},
            {"type": "code", "title": "Flattening for later models", "content": "image = torch.zeros(1, 28, 28)\nflat = image.flatten()\nprint(flat.shape)  # (784,)"},
            {"type": "paragraph", "content": "Flattening is common when moving from a spatial representation into a simple fully connected layer. For example, an image might start with height and width dimensions, but a basic linear layer often expects one long feature vector."},
            {"type": "paragraph", "content": "Reshape, squeeze, unsqueeze, and flatten are all examples of structural operations. They usually do not change the numeric values themselves. They change how PyTorch interprets those values across dimensions."},
            {"type": "code", "title": "Worked example: shape changes step by step", "content": "x = torch.tensor([1.0, 2.0, 3.0, 4.0])\nprint(x.shape)                # (4,)\nx = x.reshape(2, 2)\nprint(x.shape)                # (2, 2)\nx = x.unsqueeze(0)\nprint(x.shape)                # (1, 2, 2)\nx = x.flatten()\nprint(x.shape)                # (4,)"},
            {"type": "paragraph", "content": "A good shape habit is to narrate the meaning of each step. In the example above, the same four values move from a flat vector to a 2x2 matrix, then to a batch of one matrix, then back to a flat vector."},
            {"type": "callout", "title": "Common shape mistakes", "content": "Using `(n,)` when the code really expects `(n, 1)`, flattening too early, squeezing away a batch dimension by accident, and assuming broadcasting will work without checking dimensions are the most common mistakes."},
            {"type": "list", "title": "Recap checkpoint", "items": ["Can you explain the difference between `(3,)`, `(1, 3)`, and `(3, 1)`?", "Can you add and remove singleton dimensions intentionally?", "Can you predict the output shape of a broadcasted add?", "Can you explain what flattening preserves and what it changes?"]},
            {"type": "callout", "title": "Shape debugging habit", "content": "When code fails, print the shape before and after each operation. A few `print(x.shape)` lines are often the fastest way to understand what went wrong."},
            {"type": "callout", "title": "Why this chapter matters later", "content": "CNNs, vision models, and transformers all depend heavily on correct dimensions. If shape changes feel mechanical here, later architectures stop looking magical and start looking readable."},
            {"type": "callout", "title": "Common confusion", "content": "Shape `(3,)` is not the same as shape `(3, 1)` or `(1, 3)`. They contain the same count of values, but they behave differently in matrix multiplication and broadcasting."},
        ],
    },
    {
        "id": "02",
        "number": "02",
        "title": "Linear Regression From Scratch",
        "lesson": "02_linear_regression_from_scratch",
        "summary": "Build a regression model with raw tensors so the forward pass and loss are fully visible.",
        "image": "02_linear_regression_plot.png",
        "script_path": "tutorials/02_linear_regression_from_scratch.py",
        "pdf_path": "tutorials/pdfs/02_linear_regression_from_scratch.pdf",
        "question_ids": ["q03_linear_model", "q04_mse_loss", "q15_make_linear_params", "q16_compute_residuals", "q17_apply_sgd_update"],
        "previous_chapter": "01",
        "next_chapter": "03",
        "sections": [
            {"type": "paragraph", "content": "Linear regression is the cleanest place to learn supervised learning. You pick a formula, compare prediction to target, compute a loss, and update the parameters."},
            {"type": "code", "title": "Model formula", "content": "preds = x @ weight + bias\nloss = ((preds - targets) ** 2).mean()"},
            {"type": "list", "title": "Shape story", "items": ["x shape (batch, 1)", "weight shape (1, 1)", "bias shape (1,)", "preds shape (batch, 1)"]},
            {"type": "paragraph", "content": "This chapter matters because it exposes every moving part. Nothing is hidden behind `nn.Module` yet. You directly create the weight and bias tensors, run the forward pass, compute the loss, call `backward()`, and update the parameters yourself."},
            {"type": "list", "title": "Training loop pieces", "items": ["Input features `x` hold the known information.", "Targets `y` hold the correct answers.", "The model produces predictions.", "The loss measures how wrong those predictions are.", "Gradient descent nudges the parameters to reduce the loss."]},
            {"type": "code", "title": "A full manual step", "content": "preds = x @ weight + bias\nloss = ((preds - y) ** 2).mean()\nloss.backward()\nwith torch.no_grad():\n    weight -= lr * weight.grad\n    bias -= lr * bias.grad\nweight.grad.zero_()\nbias.grad.zero_()"},
            {"type": "paragraph", "content": "In one-feature linear regression, the model is learning the slope and intercept of a line. Weight controls how strongly the input changes the prediction. Bias shifts the whole line upward or downward. Training is just repeated small corrections to those two values."},
            {"type": "code", "title": "Line intuition", "content": "pred = weight * x + bias\n# bigger weight -> steeper line\n# bigger bias   -> line shifts upward"},
            {"type": "paragraph", "content": "If you remember school algebra, this is the same idea as `y = mx + b`. Here `m` is the weight and `b` is the bias. PyTorch is just learning those values automatically from data instead of you choosing them by hand."},
            {"type": "paragraph", "content": "The residual is `preds - targets`. It tells you the signed error. Positive residual means the model predicted too high. Negative residual means the model predicted too low. Squaring the residual removes the sign and penalizes larger mistakes more heavily."},
            {"type": "code", "title": "Residual example", "content": "preds = torch.tensor([[8.0], [4.0]])\ntargets = torch.tensor([[5.0], [6.0]])\nresiduals = preds - targets\n# tensor([[ 3.0],\n#         [-2.0]])"},
            {"type": "paragraph", "content": "The loss is the number the optimizer cares about. A lower loss means the model predictions match the targets better overall. During training, you are not directly telling the model what the right weight is. You are telling it how wrong it currently is, and gradient descent uses that signal."},
            {"type": "code", "title": "Creating trainable parameters", "content": "weight = torch.randn(1, 1, requires_grad=True)\nbias = torch.zeros(1, requires_grad=True)"},
            {"type": "list", "title": "What changes during one training step", "items": ["The forward pass computes predictions.", "The loss compares predictions to targets.", "Backward computes gradients with respect to weight and bias.", "The update changes weight and bias slightly.", "The next forward pass uses the new parameter values."]},
            {"type": "paragraph", "content": "The gradient tells you direction, not the final answer. A positive gradient means increasing that parameter would increase the loss locally, so gradient descent moves the parameter downward. A negative gradient means increasing the parameter would reduce the loss locally, so gradient descent moves it upward."},
            {"type": "code", "title": "Why subtract the gradient", "content": "parameter = parameter - learning_rate * gradient"},
            {"type": "paragraph", "content": "That subtraction rule is why the method is called gradient descent. The gradient points uphill, toward increasing loss. Subtracting the gradient moves downhill, toward lower loss. The learning rate controls how big a step you take."},
            {"type": "paragraph", "content": "For mean squared error, the math strongly punishes large mistakes because errors are squared. If one prediction is off by 10 and another is off by 1, the first contributes 100 to the squared error while the second contributes only 1."},
            {"type": "math", "title": "MSE In Math Form", "content": "MSE = (1/n) Σᵢ (ŷᵢ - yᵢ)²"},
            {"type": "math", "title": "Gradient-Descent Sign Rule", "content": "∂L/∂w > 0  ⇒  increase in w raises L  ⇒  move w downward\n∂L/∂w < 0  ⇒  increase in w lowers L   ⇒  move w upward\n\nw ← w - η · ∂L/∂w"},
            {"type": "code", "title": "Worked example: one full regression step", "content": "x = torch.tensor([[1.0], [2.0]])\ny = torch.tensor([[3.0], [5.0]])\nweight = torch.tensor([[1.0]], requires_grad=True)\nbias = torch.tensor([0.0], requires_grad=True)\n\npreds = x @ weight + bias\nloss = ((preds - y) ** 2).mean()\nloss.backward()"},
            {"type": "paragraph", "content": "In that worked example, the predictions are too low, so the gradients should push the parameters in a direction that increases the model outputs. Looking at whether predictions are too high or too low is a useful sanity check before you even inspect the exact gradient values."},
            {"type": "callout", "title": "Common mistakes in manual regression", "content": "Wrong tensor shapes for `x @ weight`, forgetting `requires_grad=True`, forgetting to clear gradients, and updating parameters without `torch.no_grad()` are the most common mistakes."},
            {"type": "list", "title": "Recap checkpoint", "items": ["Can you explain what weight and bias do in a linear model?", "Can you compute residuals and MSE from predictions and targets?", "Can you explain why subtracting the gradient moves downhill?", "Can you describe one full manual training step in order?"]},
            {"type": "callout", "title": "Why MSE uses a mean", "content": "A mean loss stays on a similar scale even if the batch size changes. Without the mean, the loss would automatically grow when you use more examples in a batch."},
            {"type": "callout", "title": "How to read improvement", "content": "If the loss is going down across steps, the model is generally learning. If it explodes or becomes `nan`, the learning rate may be too high or the computation may be unstable."},
            {"type": "callout", "title": "Most common bug here", "content": "Forgetting `torch.no_grad()` during the parameter update creates a graph through the update itself. That usually causes confusing autograd behavior later."},
        ],
    },
    {
        "id": "03",
        "number": "03",
        "title": "Linear Regression With nn.Module",
        "lesson": "03_linear_regression_with_nn_module",
        "summary": "See the same regression problem expressed with nn.Module, DataLoader, and an optimizer.",
        "image": "05_perceptron.png",
        "script_path": "tutorials/03_linear_regression_with_nn_module.py",
        "pdf_path": "tutorials/pdfs/03_linear_regression_with_nn_module.pdf",
        "question_ids": ["q05_tiny_linear_forward", "q18_build_linear_layer", "q19_make_regression_loader", "q20_compute_mse_loss", "q21_run_training_step"],
        "previous_chapter": "02",
        "next_chapter": "04",
        "sections": [
            {"type": "paragraph", "content": "Nothing magical happens inside nn.Module. PyTorch just packages trainable tensors, the forward pass, and optimizer-friendly parameter access in a cleaner abstraction."},
            {"type": "code", "title": "Standard training pattern", "content": "preds = model(batch_x)\nloss = loss_fn(preds, batch_y)\noptimizer.zero_grad()\nloss.backward()\noptimizer.step()"},
            {"type": "paragraph", "content": "This chapter is the same learning problem as the previous one, but organized using PyTorch's standard abstractions. Instead of manually storing `weight` and `bias`, you define a module. Instead of manually stepping each tensor, you use an optimizer."},
            {"type": "list", "title": "What nn.Module gives you", "items": ["A place to define layers in `__init__`.", "A `forward()` method that describes the computation.", "Automatic parameter registration so optimizers can find trainable weights.", "Cleaner code once models get bigger than one formula."]},
            {"type": "code", "title": "Minimal module", "content": "class TinyLinearModel(nn.Module):\n    def __init__(self):\n        super().__init__()\n        self.linear = nn.Linear(1, 1)\n\n    def forward(self, x):\n        return self.linear(x)"},
            {"type": "paragraph", "content": "A module is really just a Python object with trainable tensors attached to it. Calling the module runs `forward()`. The optimizer then asks the module for its parameters and updates them after gradients are computed."},
            {"type": "list", "title": "How the pieces fit together", "items": ["The model maps inputs to predictions.", "The loss function scores those predictions.", "The optimizer updates model parameters.", "The dataloader keeps feeding fresh mini-batches into this loop."]},
            {"type": "paragraph", "content": "A `DataLoader` groups examples into batches. That matters because training usually happens on many examples at once, not one sample at a time. The loader also handles shuffling so the model does not always see data in exactly the same order."},
            {"type": "code", "title": "Batch training flow", "content": "for batch_x, batch_y in loader:\n    preds = model(batch_x)\n    loss = loss_fn(preds, batch_y)\n    optimizer.zero_grad()\n    loss.backward()\n    optimizer.step()"},
            {"type": "paragraph", "content": "Notice that the overall mathematical story did not change from the manual chapter. Only the code organization changed. The model still computes predictions, the loss still measures error, and gradient descent still updates parameters."},
            {"type": "paragraph", "content": "Notice how much shorter the training loop becomes once PyTorch owns the parameter bookkeeping. That is the main reason `nn.Module` is used everywhere. It lets you scale from one linear layer to deep networks without changing the overall training pattern."},
            {"type": "code", "title": "Tiny regression dataloader", "content": "dataset = TensorDataset(x, y)\nloader = DataLoader(dataset, batch_size=32, shuffle=True)"},
            {"type": "code", "title": "Parameter inspection", "content": "for name, param in model.named_parameters():\n    print(name, param.shape)"},
            {"type": "paragraph", "content": "An optimizer like SGD is basically a helper that performs the update rule for every trainable parameter in the model. Instead of writing separate update lines for each tensor, you call `optimizer.step()` and let PyTorch handle the loop over parameters."},
            {"type": "code", "title": "What optimizer.step() is conceptually doing", "content": "for parameter in model.parameters():\n    parameter -= learning_rate * parameter.grad"},
            {"type": "paragraph", "content": "Why call `optimizer.zero_grad()` before `backward()`? Because gradients accumulate by default in PyTorch. If you skip zeroing, the next backward pass adds new gradients on top of old ones, which is usually not what you want in a standard training loop."},
            {"type": "code", "title": "Worked example: module training step", "content": "model = nn.Linear(1, 1)\nloss_fn = nn.MSELoss()\noptimizer = torch.optim.SGD(model.parameters(), lr=0.1)\n\npreds = model(batch_x)\nloss = loss_fn(preds, batch_y)\noptimizer.zero_grad()\nloss.backward()\noptimizer.step()"},
            {"type": "paragraph", "content": "Even though the code is shorter here, the meaning is the same as in the manual chapter. The difference is mostly about abstraction and organization, not different mathematics."},
            {"type": "callout", "title": "Common mistakes with nn.Module training", "content": "Creating layers inside `forward()`, forgetting `optimizer.zero_grad()`, mismatching batch shapes, and confusing the model object with its output tensor are common beginner mistakes."},
            {"type": "list", "title": "Recap checkpoint", "items": ["Can you explain what `nn.Module` stores for you?", "Can you explain what `optimizer.step()` is conceptually doing?", "Can you explain why `DataLoader` is useful?", "Can you describe the normal forward/loss/backward/step loop?"]},
            {"type": "callout", "title": "Important training order", "content": "A safe default order is: forward, loss, zero_grad, backward, step. Many bugs in beginner training code come from getting that order wrong."},
            {"type": "callout", "title": "Mental model", "content": "Modules organize parameters. Loss functions score predictions. Optimizers update parameters using the gradients that autograd computed."},
            {"type": "callout", "title": "Why DataLoader matters", "content": "Once datasets get large, loading everything manually becomes messy. `DataLoader` standardizes batching, shuffling, and iteration so model code stays clean."},
            {"type": "callout", "title": "Beginner mistake", "content": "Do not create new layers inside `forward()`. Define them once in `__init__`. Otherwise the model creates fresh random weights every time it runs."},
        ],
    },
    {
        "id": "04",
        "number": "04",
        "title": "Logistic Regression From Scratch",
        "lesson": "04_logistic_regression_from_scratch",
        "summary": "Move from regression to binary classification with logits, sigmoid, and binary cross-entropy.",
        "image": "04_logistic_curve.png",
        "script_path": "tutorials/04_logistic_regression_from_scratch.py",
        "pdf_path": "tutorials/pdfs/04_logistic_regression_from_scratch.pdf",
        "question_ids": ["q06_logistic_probability", "q22_sigmoid_function", "q23_threshold_predictions", "q24_make_binary_labels", "q25_binary_cross_entropy"],
        "previous_chapter": "03",
        "next_chapter": "05",
        "sections": [
            {"type": "paragraph", "content": "Logistic regression still starts with a linear formula, but now you interpret the output as a probability by applying sigmoid to the raw logit."},
            {"type": "code", "title": "Probability path", "content": "logits = x @ weight + bias\nprobs = torch.sigmoid(logits)"},
            {"type": "callout", "title": "Important distinction", "content": "A logit is any real number. A probability must lie between 0 and 1."},
            {"type": "paragraph", "content": "Regression predicts continuous values like price or temperature. Logistic regression predicts the probability of one class, often written as 0 vs 1. The math starts similarly, but the interpretation is different."},
            {"type": "list", "title": "Classification pipeline", "items": ["Compute a linear score called a logit.", "Apply sigmoid to convert the logit to a probability.", "Compare that probability to the true label.", "Use binary cross-entropy to penalize wrong confident predictions."]},
            {"type": "code", "title": "Thresholding probabilities", "content": "probs = torch.sigmoid(logits)\npreds = (probs >= 0.5).float()"},
            {"type": "paragraph", "content": "Sigmoid takes any real number and squashes it into the range 0 to 1. Large positive logits become probabilities near 1. Large negative logits become probabilities near 0. A logit of 0 maps to probability 0.5, which sits right at the decision boundary."},
            {"type": "code", "title": "Reading logits", "content": "torch.sigmoid(torch.tensor([-4.0, 0.0, 4.0]))\n# tensor close to [0.018, 0.500, 0.982]"},
            {"type": "paragraph", "content": "That is why the sign of the logit matters so much. Positive logit pushes the prediction toward class 1. Negative logit pushes it toward class 0. The larger the magnitude, the more confident the model is."},
            {"type": "paragraph", "content": "Binary cross-entropy becomes very large when the model is confidently wrong. If the true label is 1 but the model predicts a probability close to 0, the loss should strongly punish that mistake."},
            {"type": "code", "title": "Manual BCE idea", "content": "preds = preds.clamp(1e-7, 1 - 1e-7)\nloss = -(targets * torch.log(preds) + (1 - targets) * torch.log(1 - preds)).mean()"},
            {"type": "paragraph", "content": "The BCE formula has two parts. One part is active when the label is 1 and asks the model to make `log(pred)` large, which means `pred` should be close to 1. The other part is active when the label is 0 and asks the model to make `log(1 - pred)` large, which means `pred` should be close to 0."},
            {"type": "math", "title": "BCE In Math Form", "content": "BCE = -[y log(p) + (1 - y) log(1 - p)]"},
            {"type": "list", "title": "How to read class outputs", "items": ["Probability near 0 means strong belief in class 0.", "Probability near 1 means strong belief in class 1.", "Probability near 0.5 means the model is uncertain.", "Thresholding converts probabilities into hard class decisions."]},
            {"type": "code", "title": "Making binary labels", "content": "scores = torch.tensor([-2.0, 0.3, 1.7])\nlabels = (scores > 0).float().unsqueeze(1)"},
            {"type": "paragraph", "content": "Classification labels are usually stored as 0 and 1. The model does not directly emit those labels during training. It emits probabilities, because probabilities provide a smoother learning signal for gradient-based optimization."},
            {"type": "paragraph", "content": "This matters for gradients too. A hard threshold like `(probs >= 0.5)` is fine for evaluation, but it is not the object you want inside the training loss. The smooth probability is what lets gradient-based learning work well."},
            {"type": "math", "title": "Sigmoid At Zero", "content": "σ(z) = 1 / (1 + e⁻ᶻ)\nσ(0) = 1 / (1 + e⁰)\n     = 1 / (1 + 1)\n     = 1/2 = 0.5"},
            {"type": "code", "title": "Worked example: logistic probability and threshold", "content": "logits = torch.tensor([[-2.0], [0.0], [2.0]])\nprobs = torch.sigmoid(logits)\npreds = (probs >= 0.5).float()"},
            {"type": "paragraph", "content": "That worked example shows the full interpretation chain: raw score -> probability -> hard class. During learning, the probability is the important smooth quantity. During reporting, the hard class is often what people want to see."},
            {"type": "callout", "title": "Common mistakes in manual logistic regression", "content": "Using hard thresholded predictions inside the training loss, forgetting that probabilities must lie in `[0, 1]`, and mixing up logits with probabilities are the most common mistakes."},
            {"type": "list", "title": "Recap checkpoint", "items": ["Can you explain what a logit is?", "Can you explain why sigmoid maps to the interval `[0, 1]`?", "Can you explain why BCE punishes confident wrong predictions strongly?", "Can you explain why thresholding is for evaluation, not for the training loss?"]},
            {"type": "callout", "title": "Math intuition", "content": "When the model is confident and correct, BCE becomes small. When the model is confident and wrong, BCE becomes large. That is exactly the behavior you want from a classification loss."},
            {"type": "callout", "title": "Why clamping matters", "content": "If a predicted probability becomes exactly 0 or 1, taking a log can cause numerical trouble. Clamping avoids `log(0)` in the manual formula."},
            {"type": "callout", "title": "Why probabilities help learning", "content": "A hard 0 or 1 class prediction throws away uncertainty. A probability like 0.62 tells you much more about how the model currently feels, which makes it more useful inside a differentiable loss."},
            {"type": "callout", "title": "Common confusion", "content": "A class prediction like 0 or 1 is not the same thing as a probability. The probability is the model's confidence before thresholding."},
        ],
    },
    {
        "id": "05",
        "number": "05",
        "title": "Logistic Regression With nn.Module",
        "lesson": "05_logistic_regression_with_nn_module",
        "summary": "Use nn.Linear and BCEWithLogitsLoss so PyTorch handles the standard binary-classification stack.",
        "image": "05_perceptron.png",
        "script_path": "tutorials/05_logistic_regression_with_nn_module.py",
        "pdf_path": "tutorials/pdfs/05_logistic_regression_with_nn_module.pdf",
        "question_ids": ["q07_logistic_module_forward", "q26_build_logistic_layer", "q27_logits_to_probs", "q28_make_bce_loss", "q29_predict_binary_classes"],
        "previous_chapter": "04",
        "next_chapter": None,
        "sections": [
            {"type": "paragraph", "content": "In PyTorch you usually return raw logits from forward() and let BCEWithLogitsLoss handle the stable sigmoid-plus-loss computation during training."},
            {"type": "list", "title": "What to remember", "items": ["forward() returns logits, not probabilities", "torch.sigmoid is for interpretation during evaluation", "labels should match the output shape"]},
            {"type": "paragraph", "content": "This chapter repeats the previous classification idea with PyTorch's standard building blocks. The key improvement is numerical stability. `BCEWithLogitsLoss` combines the sigmoid step and the BCE calculation in a way that is more stable than manually doing both during training."},
            {"type": "code", "title": "Standard model and loss", "content": "model = nn.Linear(2, 1)\nloss_fn = nn.BCEWithLogitsLoss()\nlogits = model(x)\nloss = loss_fn(logits, y)"},
            {"type": "paragraph", "content": "This is a good example of a common PyTorch design pattern: keep the model output simple and let the loss function handle the numerically tricky transformation. That is why many models return logits, not already-processed probabilities."},
            {"type": "paragraph", "content": "Notice the difference between training and evaluation. During training, the loss function wants logits. During evaluation, a human usually wants probabilities or class labels, so you apply `torch.sigmoid` yourself after the forward pass."},
            {"type": "code", "title": "Evaluation flow", "content": "logits = model(x)\nprobs = torch.sigmoid(logits)\npreds = (probs >= 0.5).float()"},
            {"type": "list", "title": "Why this pattern is preferred", "items": ["The model stays simple: it only returns logits.", "The loss function handles the numerically sensitive part.", "You can still turn logits into probabilities when you want to inspect predictions."]},
            {"type": "paragraph", "content": "Numerical stability sounds abstract, but the practical idea is simple: some formulas are mathematically correct yet fragile on a computer. `BCEWithLogitsLoss` uses a more stable internal form than manually doing `sigmoid` followed by `log`, especially for very large positive or negative logits."},
            {"type": "paragraph", "content": "In practice, this pattern scales from logistic regression to much larger neural networks. Even deep classifiers often return logits first, and the training loss is responsible for converting them into a stable objective."},
            {"type": "code", "title": "Logits to probabilities", "content": "logits = torch.tensor([[-1.0], [0.0], [1.0]])\nprobs = torch.sigmoid(logits)\npreds = (probs >= 0.5).float()"},
            {"type": "code", "title": "Typical training step", "content": "logits = model(batch_x)\nloss = loss_fn(logits, batch_y)\noptimizer.zero_grad()\nloss.backward()\noptimizer.step()"},
            {"type": "list", "title": "Train vs evaluate checklist", "items": ["Training: model returns logits.", "Training: use BCEWithLogitsLoss on those logits.", "Evaluation: apply sigmoid if you want probabilities.", "Evaluation: threshold probabilities if you want hard class predictions."]},
            {"type": "paragraph", "content": "A useful way to think about this chapter is that the model and the loss have a contract. The model promises to output logits. The loss promises to interpret those logits correctly during training. Breaking that contract is what causes the common double-sigmoid mistake."},
            {"type": "code", "title": "Correct separation of responsibilities", "content": "class Model(nn.Module):\n    def forward(self, x):\n        return self.linear(x)   # logits only\n\nloss = nn.BCEWithLogitsLoss()(logits, labels)"},
            {"type": "code", "title": "Worked example: stable classification training step", "content": "model = nn.Linear(2, 1)\nloss_fn = nn.BCEWithLogitsLoss()\noptimizer = torch.optim.SGD(model.parameters(), lr=0.1)\n\nlogits = model(batch_x)\nloss = loss_fn(logits, batch_y)\noptimizer.zero_grad()\nloss.backward()\noptimizer.step()"},
            {"type": "paragraph", "content": "This chapter is really about separating concerns cleanly. The model returns logits. The loss handles training-time stability. Evaluation code turns logits into probabilities and class labels only when needed."},
            {"type": "callout", "title": "Common mistakes with BCEWithLogitsLoss", "content": "Applying sigmoid inside `forward()`, passing labels with the wrong shape, and confusing evaluation-time probabilities with training-time logits are the most common mistakes."},
            {"type": "list", "title": "Recap checkpoint", "items": ["Can you explain why `BCEWithLogitsLoss` expects logits?", "Can you explain why applying sigmoid twice is wrong?", "Can you describe the difference between training-time outputs and evaluation-time outputs?", "Can you explain how logits become probabilities and then classes?"]},
            {"type": "callout", "title": "Gradient intuition here", "content": "Even though you are using higher-level building blocks, the same gradient logic still applies. Backward computes how each weight change would affect the classification loss, and the optimizer uses that information to update the weights."},
            {"type": "callout", "title": "Very common bug", "content": "Do not apply `sigmoid` inside `forward()` and then also use `BCEWithLogitsLoss`. That would effectively apply the sigmoid logic twice."},
            {"type": "callout", "title": "Why this chapter matters later", "content": "The same separation between raw model outputs and interpretation shows up again in later architectures. Learning it here makes more advanced models feel less mysterious."},
            {"type": "callout", "title": "Shape reminder", "content": "If the model output is shape `(batch, 1)`, your labels should usually also be shape `(batch, 1)`, not `(batch,)`."},
        ],
    },
]


CHAPTERS_BY_ID = {chapter["id"]: chapter for chapter in CHAPTERS}


def public_chapter_summaries() -> list[dict[str, object]]:
    return [
        {
            "id": chapter["id"],
            "number": chapter["number"],
            "title": chapter["title"],
            "lesson": chapter["lesson"],
            "summary": chapter["summary"],
            "image": chapter["image"],
            "question_count": len(chapter["question_ids"]),
        }
        for chapter in CHAPTERS
    ]


def get_chapter(chapter_id: str) -> dict[str, object] | None:
    chapter = CHAPTERS_BY_ID.get(chapter_id)
    if chapter is None:
        return None
    return deepcopy(chapter)
