from __future__ import annotations

from copy import deepcopy


CHAPTERS = [
    {
        "id": "00",
        "number": "00",
        "title": "Tensors and Autograd",
        "lesson": "00_tensors_and_autograd",
        "summary": "Start from absolute basics: create tensors, inspect shapes, dtypes, slicing, simple reductions, constructors like `arange` and `linspace`, selection operations like `argmax`, NumPy relation, and then learn the backward/update loop that powers training.",
        "image": "00_gradient_descent.png",
        "script_path": "tutorials/00_tensors_and_autograd.py",
        "pdf_path": "tutorials/pdfs/00_tensors_and_autograd.pdf",
        "question_ids": ["q30_create_tensor_from_list", "q31_tensor_dtype", "q32_make_zeros_tensor", "q33_slice_first_row", "q34_tensor_num_dims", "q35_sum_columns", "q00_add_tensors", "q01_trainable_scalar", "q08_matrix_multiply", "q09_tensor_mean", "q10_gradient_step"],
        "previous_chapter": None,
        "next_chapter": "01",
        "sections": [
            {"type": "paragraph", "content": "PyTorch revolves around tensors and autograd. Tensors hold numbers in a structured way, and autograd tracks how a final loss depends on trainable values."},
            {"type": "paragraph", "content": "If you are brand new, start with three things: how to create a tensor, how to inspect its shape, and how to inspect its dtype. Those three ideas show up in almost every PyTorch program."},
            {"type": "list", "title": "What to understand first", "items": ["A scalar has shape (). A vector may have shape (3,). A matrix may have shape (2, 2).", "A dtype tells PyTorch what kind of numbers the tensor stores, such as integers or floating point values.", "Elementwise operations keep the same shape when the inputs match.", "Calling backward() computes gradients for tensors with requires_grad=True."]},
            {"type": "code", "title": "Creating basic tensors", "content": "x = torch.tensor([1.0, 2.0, 3.0])\nprint(x.shape)   # torch.Size([3])\nprint(x.dtype)   # torch.float32 by default for these values\ny = torch.zeros(2, 3)"},
            {"type": "paragraph", "content": "A tensor is just a container for numbers plus metadata. The metadata matters. Shape tells you how the values are arranged. Dtype tells you the numeric kind. Device tells you where the tensor lives, such as CPU or later MPS on your Mac."},
            {"type": "paragraph", "content": "If you already know NumPy arrays, PyTorch tensors will feel familiar. Both represent n-dimensional blocks of numbers and support indexing, slicing, reshaping, and vectorized math. The big extra thing in PyTorch is autograd and deep-learning layers."},
            {"type": "list", "title": "NumPy and PyTorch side by side", "items": ["NumPy uses `np.array(...)`; PyTorch uses `torch.tensor(...)`.", "NumPy is widely used for general numerical work.", "PyTorch tensors can participate in autograd when `requires_grad=True`.", "PyTorch models and optimizers are built around tensors, so tensors are the natural object for deep learning."]},
            {"type": "list", "title": "Common tensor constructors", "items": ["torch.tensor([...]) builds a tensor from Python values.", "torch.zeros(rows, cols) builds a tensor full of zeros.", "torch.ones(...) builds a tensor full of ones.", "torch.arange(start, end) builds a simple counting tensor.", "`torch.linspace(start, end, steps=...)` builds evenly spaced values across an interval."]},
            {"type": "paragraph", "content": "Beginners often meet `arange` and `linspace` around the same time, but they are slightly different ideas. `arange` counts with a step pattern, while `linspace` asks for a fixed number of evenly spaced values between two endpoints. Both are useful, but `linspace` is especially nice when you want a smooth set of points for plotting or a toy dataset."},
            {"type": "code", "title": "arange vs linspace", "content": "counting = torch.arange(0, 5)\nprint(counting)   # tensor([0, 1, 2, 3, 4])\n\nspaced = torch.linspace(0, 1, steps=5)\nprint(spaced)     # tensor([0.0000, 0.2500, 0.5000, 0.7500, 1.0000])"},
            {"type": "paragraph", "content": "One useful beginner habit is to separate the ideas of data and operations. A tensor is the data. Operations like add, multiply, sum, reshape, and slice transform that data. Most PyTorch code is just a sequence of tensor operations applied in the right order."},
            {"type": "code", "title": "Inspecting tensor metadata", "content": "x = torch.tensor([[1, 2], [3, 4]], dtype=torch.float32)\nprint(x)\nprint(x.shape)   # torch.Size([2, 2])\nprint(x.dtype)   # torch.float32\nprint(x.ndim)    # 2 dimensions"},
            {"type": "paragraph", "content": "Dtype matters more than beginners expect. Integer tensors are fine for indexes or labels, but many training computations need floating point tensors because gradients and parameter updates involve decimal values. If a result looks strange, checking `x.dtype` is often worthwhile."},
            {"type": "code", "title": "Integer vs float tensors", "content": "ints = torch.tensor([1, 2, 3])\nprint(ints.dtype)  # often torch.int64\nfloats = torch.tensor([1, 2, 3], dtype=torch.float32)\nprint(floats.dtype)  # torch.float32"},
            {"type": "paragraph", "content": "Floating point tensors also come in different precisions. The most common one in PyTorch is `torch.float32`. You will also see `torch.float16` which is often called half precision or just half, and `torch.float64` which is often called double precision or just double."},
            {"type": "list", "title": "Common floating point dtypes", "items": ["`torch.float16` or half: uses less memory, lower precision.", "`torch.float32`: the default for most training and the most common choice.", "`torch.float64` or double: higher precision, more memory, often used in scientific or debugging contexts."]},
            {"type": "code", "title": "Half, float, and double", "content": "half_tensor = torch.tensor([1.0, 2.0], dtype=torch.float16)\nfloat_tensor = torch.tensor([1.0, 2.0], dtype=torch.float32)\ndouble_tensor = torch.tensor([1.0, 2.0], dtype=torch.float64)\n\nprint(half_tensor.dtype)    # torch.float16\nprint(float_tensor.dtype)   # torch.float32\nprint(double_tensor.dtype)  # torch.float64"},
            {"type": "paragraph", "content": "Higher precision means numbers can be represented more accurately, but it also costs more memory and usually more compute. Lower precision saves memory and can be faster on some hardware, but very small numeric differences may be lost. That tradeoff is why dtype matters in real training systems."},
            {"type": "paragraph", "content": "For a beginner learning on CPU, `torch.float32` is the best default. It is the standard choice in most beginner tutorials and examples. Half precision becomes more important later when people optimize large models on GPUs. Double precision is helpful when you want extra numerical accuracy, but it is not the usual default in deep learning."},
            {"type": "code", "title": "Changing dtype", "content": "x = torch.tensor([1, 2, 3])\nprint(x.dtype)\n\nx_float = x.float()      # convert to float32\nx_half = x.half()        # convert to float16\nx_double = x.double()    # convert to float64\n\nprint(x_float.dtype)\nprint(x_half.dtype)\nprint(x_double.dtype)"},
            {"type": "paragraph", "content": "The names `half()`, `float()`, and `double()` are just convenient conversions. They are shorthand for converting a tensor to `float16`, `float32`, and `float64`. You can also use `.to(dtype=...)` when you want a more general conversion style."},
            {"type": "code", "title": "Converting with .to()", "content": "x = torch.tensor([1, 2, 3])\nx = x.to(dtype=torch.float32)\nprint(x.dtype)"},
            {"type": "callout", "title": "Practical rule", "content": "If you are unsure, use `torch.float32`. That is the safest and most common dtype for beginner PyTorch code."},
            {"type": "callout", "title": "Why half is not the default here", "content": "Half precision can be useful for speed and memory savings, but it is easier to run into numerical issues and hardware-specific behavior. For learning fundamentals on CPU, it is usually more trouble than benefit."},
            {"type": "callout", "title": "Why double exists", "content": "Double precision keeps more numerical detail. It can help in some scientific calculations or debugging tiny numerical differences, but it is usually not necessary for standard beginner neural network training."},
            {"type": "paragraph", "content": "Slicing a tensor means selecting part of it with bracket notation. This is one of the most basic and most useful skills in numerical computing. You can take one row, one column, or a smaller block from a bigger tensor."},
            {"type": "code", "title": "Basic slicing examples", "content": "x = torch.tensor([[10, 20, 30], [40, 50, 60]])\nprint(x[0])      # first row -> tensor([10, 20, 30])\nprint(x[:, 1])   # second column -> tensor([20, 50])\nprint(x[0, 2])   # single value -> tensor(30)"},
            {"type": "paragraph", "content": "Indexing with a single integer removes that dimension from the result. That is why `x[0]` returns one row and has fewer dimensions than the original matrix. This behavior becomes important later when a model expects a batch dimension and you accidentally index it away."},
            {"type": "paragraph", "content": "A dimension is just an axis. For a matrix of shape `(2, 3)`, dimension 0 points across rows and dimension 1 points across columns. That is why summing with `dim=0` collapses rows and gives one value per column, while `dim=1` collapses columns and gives one value per row."},
            {"type": "code", "title": "Simple reduction operations", "content": "x = torch.tensor([[1.0, 2.0], [3.0, 4.0]])\nprint(x.sum())        # 10.0\nprint(x.sum(dim=0))   # tensor([4.0, 6.0])\nprint(x.sum(dim=1))   # tensor([3.0, 7.0])\nprint(x.mean())       # 2.5"},
            {"type": "list", "title": "Basic tensor operations worth memorizing", "items": ["`x.sum()` adds values.", "`x.mean()` averages values.", "`x.max()` returns the largest value.", "`x.min()` returns the smallest value.", "`x.argmax()` returns the index of the largest value.", "`x.ndim` tells you how many dimensions the tensor has."]},
            {"type": "paragraph", "content": "You can think of `sum`, `mean`, `max`, and `min` as reduction operations. They reduce many values down to fewer values. Reductions are common in machine learning because a model often produces many per-example numbers, and then a loss function reduces them to one scalar objective."},
            {"type": "paragraph", "content": "`argmax` is slightly different from `max`. `max` gives you the largest value. `argmax` gives you the position of that largest value. That distinction becomes important later when a classifier produces one score per class and you want the predicted class index, not just the score itself."},
            {"type": "code", "title": "max vs argmax", "content": "scores = torch.tensor([0.1, 2.4, 1.7])\nprint(scores.max())      # tensor(2.4)\nprint(scores.argmax())   # tensor(1) because index 1 holds the largest value\n\nlogits = torch.tensor([[1.2, 0.3, 2.8], [0.1, 3.4, 0.2]])\nprint(logits.argmax(dim=1))   # tensor([2, 1])"},
            {"type": "callout", "title": "Argmax later in the course", "content": "You will use `argmax` a lot for classification, where each output position represents a class and the largest score wins. Max pooling is related in spirit because it keeps the largest value in a local region, but the pooling layer itself is about the max values, not usually about you manually calling `argmax` in beginner CNN code."},
            {"type": "paragraph", "content": "Autograd becomes important once a tensor represents something trainable, such as a weight. When `requires_grad=True`, PyTorch remembers the operations used to produce a result. After you call `backward()`, PyTorch fills `.grad` on the leaf tensors that need updates."},
            {"type": "paragraph", "content": "A useful mental model is that autograd builds a computation history while your code runs forward. Then `backward()` walks that history in reverse to compute gradients. You usually do not need to derive those gradients by hand, but you do need to know which tensors should track them."},
            {"type": "math", "title": "Symbolic Derivative Example", "content": "f(x) = x² + 2x + 10\nf′(x) = 2x + 2\n\nx = 3\nf′(3) = 2·3 + 2 = 8"},
            {"type": "code", "title": "Polynomial gradient example", "content": "x = torch.tensor(3.0, requires_grad=True)\nf = x**2 + 2*x + 10\nprint(f)           # 25.0\nprint(f.grad_fn)   # something like <AddBackward0 ...>\nf.backward()\nprint(x.grad)      # 8.0"},
            {"type": "paragraph", "content": "In that example, `grad_fn` means the current tensor was produced by some differentiable operation. PyTorch stores the local backward rule for each operation node. When you call `backward()`, PyTorch chains those local rules together using the chain rule from calculus."},
            {"type": "graph", "title": "How The Graph Looks Conceptually", "branches": [["x", "x²"], ["x", "2x"], ["10"]], "merge_label": "+", "result_chain": ["f"]},
            {"type": "math", "title": "Term-By-Term Derivative", "content": "d/dx (x² + 2x + 10)\n= d/dx (x²) + d/dx (2x) + d/dx (10)\n= 2x + 2 + 0\n= 2x + 2"},
            {"type": "paragraph", "content": "Now look at a chain-rule example. Let `z = tan(log(x^3 y^3 + xy + y^2 x))`. That expression looks intimidating, but the idea is still the same: break it into intermediate pieces and differentiate one step at a time."},
            {"type": "code", "title": "Breaking a complex expression into steps", "content": "a = x**3 * y**3\nb = x * y\nc = y**2 * x\nu = a + b + c\nv = log(u)\nz = tan(v)"},
            {"type": "paragraph", "content": "Once you define intermediates, the graph becomes easier to read. `z` depends on `v`. `v` depends on `u`. `u` depends on `a`, `b`, and `c`. And those depend on `x` and `y`. Autograd stores this graph automatically while your code runs forward."},
            {"type": "graph", "title": "Complex Graph Idea", "branches": [["x, y", "a = x³y³"], ["x, y", "b = xy"], ["x, y", "c = y²x"]], "merge_label": "sum", "result_chain": ["u", "log(u)", "tan(log(u)) = z"]},
            {"type": "math", "title": "Chain Rule Pieces", "content": "z = tan(v)\nv = log(u)\nu = x³y³ + xy + y²x\n\n∂z/∂v = sec²(v)\n∂v/∂u = 1/u\n\n∂u/∂x = 3x²y³ + y + y²\n∂u/∂y = 3x³y² + x + 2yx"},
            {"type": "math", "title": "Chain Rule Result", "content": "dz/dx = sec²(log(u)) · (1/u) · (3x²y³ + y + y²)\ndz/dy = sec²(log(u)) · (1/u) · (3x³y² + x + 2yx)\n\nu = x³y³ + xy + y²x"},
            {"type": "paragraph", "content": "That is exactly the style of work autograd is automating. It does not use magic. It applies the chain rule through the computation graph. Each node knows how to propagate gradients to its parents. PyTorch multiplies and accumulates those local gradient contributions for you."},
            {"type": "code", "title": "PyTorch version of the chain-rule example", "content": "x = torch.tensor(2.0, requires_grad=True)\ny = torch.tensor(1.5, requires_grad=True)\nz = torch.tan(torch.log(x**3 * y**3 + x*y + y**2 * x))\nprint(z.grad_fn)\nz.backward()\nprint(x.grad)\nprint(y.grad)"},
            {"type": "paragraph", "content": "A useful rule: leaf tensors are the original tensors you created directly, like `x` and `y`. Those are the tensors whose `.grad` fields PyTorch usually fills after `backward()`. Intermediate tensors like `u` or `v` usually have a `grad_fn`, but their `.grad` is not kept unless you explicitly ask for it."},
            {"type": "code", "title": "Leaf tensor idea", "content": "x = torch.tensor(2.0, requires_grad=True)\ny = x**2\nprint(x.grad_fn)  # None, because x is a leaf tensor\nprint(y.grad_fn)  # has a backward function because y came from an operation"},
            {"type": "code", "title": "Core update loop", "content": "loss.backward()\nwith torch.no_grad():\n    parameter -= learning_rate * parameter.grad\nparameter.grad.zero_()"},
            {"type": "list", "title": "Why each line in the update loop exists", "items": ["`loss.backward()` computes gradients.", "`torch.no_grad()` stops the update itself from being tracked.", "`parameter -= ...` changes the trainable value.", "`parameter.grad.zero_()` clears old gradients so the next step starts fresh."]},
            {"type": "code", "title": "Tiny autograd example", "content": "weight = torch.tensor(2.0, requires_grad=True)\nloss = (3 * weight - 9) ** 2\nloss.backward()\nprint(weight.grad)"},
            {"type": "paragraph", "content": "There is one more subtle point: gradients accumulate in `.grad`. If you call `backward()` twice without clearing `.grad`, PyTorch adds the new gradient on top of the old one. That is useful in some advanced cases, but in a normal training loop you usually want to zero the gradient before the next step."},
            {"type": "code", "title": "Why gradients are zeroed", "content": "x = torch.tensor(3.0, requires_grad=True)\ny = x**2\ny.backward()\nprint(x.grad)  # 6\n\ny = x**2\ny.backward()\nprint(x.grad)  # 12, because gradients accumulated"},
            {"type": "code", "title": "Worked example: from expression to gradient", "content": "x = torch.tensor(4.0, requires_grad=True)\ny = x**2 + 2*x + 10\n# Math says dy/dx = 2x + 2\n# At x = 4, gradient should be 10\ny.backward()\nprint(x.grad)  # 10"},
            {"type": "math", "title": "Math ↔ PyTorch Check", "content": "f(x) = x² + 2x + 10\nf′(x) = 2x + 2\n\nx = 4  ⇒  f′(4) = 10\nPyTorch: x.grad = 10"},
            {"type": "callout", "title": "Common mistakes with autograd", "content": "Forgetting `requires_grad=True`, calling `backward()` on something that is not a scalar without providing a gradient, updating parameters outside `torch.no_grad()`, and forgetting to clear `.grad` are the most common beginner mistakes."},
            {"type": "list", "title": "Recap checkpoint", "items": ["Can you explain what shape, dtype, and device mean?", "Can you create tensors with zeros, ones, `arange`, and `linspace`?", "Can you slice a row or a column from a matrix?", "Can you explain the difference between `max()` and `argmax()`?", "Can you explain what `requires_grad`, `grad_fn`, and `.grad` each mean?", "Can you explain why gradients are zeroed between training steps?"]},
            {"type": "callout", "title": "What beginners usually mix up", "content": "A tensor value is not the same thing as its gradient. The tensor stores the current parameter or data. The gradient stores how the loss changes if that parameter changes a little."},
            {"type": "callout", "title": "How to think about grad_fn", "content": "`grad_fn` is PyTorch's reminder that this tensor came from a differentiable operation. It is not the final gradient value. It is the link back into the computation graph used during backpropagation."},
            {"type": "callout", "title": "How this chapter connects to the rest", "content": "Every later model in this course, from regression to CNNs and transformers, still runs on tensors. If tensor shapes and reductions are clear, later chapters become much easier to debug."},
            {"type": "callout", "title": "Beginner focus", "content": "Before worrying about neural networks, get comfortable creating tensors, reading shape and dtype, and understanding why only trainable parameters need requires_grad=True."},
        ],
    },
    {
        "id": "01",
        "number": "01",
        "title": "Shapes, Reshape, and Gradients",
        "lesson": "01_shapes_gradients_and_reshape",
        "summary": "Practice shape thinking so matrix multiplication, reshape, and broadcasting stop feeling mysterious.",
        "image": "01_matrix_multiplication.png",
        "script_path": "tutorials/01_shapes_gradients_and_reshape.py",
        "pdf_path": "tutorials/pdfs/01_shapes_gradients_and_reshape.pdf",
        "question_ids": ["q02_reshape_to_column", "q11_add_batch_dim", "q12_remove_singleton_dim", "q13_flatten_tensor", "q14_add_bias"],
        "previous_chapter": "00",
        "next_chapter": "02",
        "sections": [
            {"type": "paragraph", "content": "Most beginner PyTorch bugs are shape bugs. If you can read a shape and predict how it changes after reshape, unsqueeze, or matrix multiplication, later chapters become much easier."},
            {"type": "list", "title": "Shape rules to memorize", "items": ["reshape changes arrangement, not values.", "unsqueeze adds a dimension of size 1.", "broadcasting lets smaller tensors expand over compatible dimensions."]},
            {"type": "code", "title": "Common reshape pattern", "content": "x = torch.tensor([1, 2, 3])\ncolumn = x.unsqueeze(1)  # shape (3, 1)"},
            {"type": "paragraph", "content": "When you see a shape like `(3, 4)`, read it out loud as '3 rows and 4 columns'. When you see `(batch, features)`, think 'one row per example, one column per feature'. Naming the meaning of each dimension makes shape bugs easier to catch."},
            {"type": "list", "title": "Core shape operations", "items": ["`unsqueeze(dim)` adds a size-1 dimension.", "`squeeze(dim)` removes a size-1 dimension.", "`reshape(...)` changes the view of the same values into a new arrangement.", "`flatten()` turns many dimensions into one long dimension."]},
            {"type": "code", "title": "Three useful examples", "content": "x = torch.tensor([1, 2, 3])\nprint(x.shape)             # (3,)\nprint(x.unsqueeze(0).shape)  # (1, 3)\nprint(x.unsqueeze(1).shape)  # (3, 1)"},
            {"type": "paragraph", "content": "A lot of shape reasoning is really about preserving meaning. If a vector holds three features for one example, shape `(3,)` is ambiguous because it does not tell PyTorch whether that dimension should behave like a row or a column. Adding an explicit batch or feature dimension often removes that ambiguity."},
            {"type": "code", "title": "Row vs column intuition", "content": "x = torch.tensor([1.0, 2.0, 3.0])\nrow = x.unsqueeze(0)     # shape (1, 3)\ncolumn = x.unsqueeze(1)  # shape (3, 1)"},
            {"type": "paragraph", "content": "That distinction becomes critical for matrix multiplication. A row vector and a column vector contain the same values, but they interact with matrices differently. In linear algebra, shape is part of the meaning, not just a storage detail."},
            {"type": "code", "title": "Why row and column are different", "content": "row = torch.tensor([1.0, 2.0, 3.0]).unsqueeze(0)     # (1, 3)\ncolumn = torch.tensor([1.0, 2.0, 3.0]).unsqueeze(1)  # (3, 1)\nprint(row.shape)\nprint(column.shape)"},
            {"type": "paragraph", "content": "Broadcasting is the rule that allows PyTorch to combine different shapes when they are compatible. For example, adding a bias vector of shape `(3,)` to a matrix of shape `(2, 3)` works because PyTorch conceptually copies that bias across both rows."},
            {"type": "code", "title": "Broadcasting example", "content": "matrix = torch.tensor([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])\nbias = torch.tensor([10.0, 20.0, 30.0])\nresult = matrix + bias"},
            {"type": "paragraph", "content": "Broadcasting does not mean PyTorch literally copies the smaller tensor in memory first. The main idea is logical expansion: PyTorch behaves as if the smaller tensor were repeated across the compatible dimension so elementwise math can happen."},
            {"type": "paragraph", "content": "A clean way to check broadcasting is to compare dimensions from the rightmost side moving left. Two dimensions are compatible if they are equal or one of them is 1. If neither rule holds, broadcasting fails."},
            {"type": "code", "title": "Right-to-left broadcasting idea", "content": "(2, 3)\n(   3)\n# compare from the right:\n# 3 with 3 -> compatible\n# missing left dimension acts like 1 -> compatible"},
            {"type": "list", "title": "A practical shape checklist", "items": ["What does each dimension mean?", "Which dimensions should stay the same after this operation?", "Which dimension am I adding, removing, or collapsing?", "If broadcasting happens, along which axis is the smaller tensor expanding?"]},
            {"type": "code", "title": "Flattening for later models", "content": "image = torch.zeros(1, 28, 28)\nflat = image.flatten()\nprint(flat.shape)  # (784,)"},
            {"type": "paragraph", "content": "Flattening is common when moving from a spatial representation into a simple fully connected layer. For example, an image might start with height and width dimensions, but a basic linear layer often expects one long feature vector."},
            {"type": "paragraph", "content": "Reshape, squeeze, unsqueeze, and flatten are all examples of structural operations. They usually do not change the numeric values themselves. They change how PyTorch interprets those values across dimensions."},
            {"type": "code", "title": "Worked example: shape changes step by step", "content": "x = torch.tensor([1.0, 2.0, 3.0, 4.0])\nprint(x.shape)                # (4,)\nx = x.reshape(2, 2)\nprint(x.shape)                # (2, 2)\nx = x.unsqueeze(0)\nprint(x.shape)                # (1, 2, 2)\nx = x.flatten()\nprint(x.shape)                # (4,)"},
            {"type": "paragraph", "content": "A good shape habit is to narrate the meaning of each step. In the example above, the same four values move from a flat vector to a 2x2 matrix, then to a batch of one matrix, then back to a flat vector."},
            {"type": "callout", "title": "Common shape mistakes", "content": "Using `(n,)` when the code really expects `(n, 1)`, flattening too early, squeezing away a batch dimension by accident, and assuming broadcasting will work without checking dimensions are the most common mistakes."},
            {"type": "list", "title": "Recap checkpoint", "items": ["Can you explain the difference between `(3,)`, `(1, 3)`, and `(3, 1)`?", "Can you add and remove singleton dimensions intentionally?", "Can you predict the output shape of a broadcasted add?", "Can you explain what flattening preserves and what it changes?"]},
            {"type": "callout", "title": "Shape debugging habit", "content": "When code fails, print the shape before and after each operation. A few `print(x.shape)` lines are often the fastest way to understand what went wrong."},
            {"type": "callout", "title": "Why this chapter matters later", "content": "CNNs, vision models, and transformers all depend heavily on correct dimensions. If shape changes feel mechanical here, later architectures stop looking magical and start looking readable."},
            {"type": "callout", "title": "Common confusion", "content": "Shape `(3,)` is not the same as shape `(3, 1)` or `(1, 3)`. They contain the same count of values, but they behave differently in matrix multiplication and broadcasting."},
        ],
    },
    {
        "id": "02",
        "number": "02",
        "title": "Linear Regression From Scratch",
        "lesson": "02_linear_regression_from_scratch",
        "summary": "Build a regression model with raw tensors so the forward pass and loss are fully visible.",
        "image": "02_linear_regression_plot.png",
        "script_path": "tutorials/02_linear_regression_from_scratch.py",
        "pdf_path": "tutorials/pdfs/02_linear_regression_from_scratch.pdf",
        "question_ids": ["q03_linear_model", "q04_mse_loss", "q15_make_linear_params", "q16_compute_residuals", "q17_apply_sgd_update"],
        "previous_chapter": "01",
        "next_chapter": "03",
        "sections": [
            {"type": "paragraph", "content": "Linear regression is the cleanest place to learn supervised learning. You pick a formula, compare prediction to target, compute a loss, and update the parameters."},
            {"type": "code", "title": "Model formula", "content": "preds = x @ weight + bias\nloss = ((preds - targets) ** 2).mean()"},
            {"type": "list", "title": "Shape story", "items": ["x shape (batch, 1)", "weight shape (1, 1)", "bias shape (1,)", "preds shape (batch, 1)"]},
            {"type": "paragraph", "content": "This chapter matters because it exposes every moving part. Nothing is hidden behind `nn.Module` yet. You directly create the weight and bias tensors, run the forward pass, compute the loss, call `backward()`, and update the parameters yourself."},
            {"type": "list", "title": "Training loop pieces", "items": ["Input features `x` hold the known information.", "Targets `y` hold the correct answers.", "The model produces predictions.", "The loss measures how wrong those predictions are.", "Gradient descent nudges the parameters to reduce the loss."]},
            {"type": "code", "title": "A full manual step", "content": "preds = x @ weight + bias\nloss = ((preds - y) ** 2).mean()\nloss.backward()\nwith torch.no_grad():\n    weight -= lr * weight.grad\n    bias -= lr * bias.grad\nweight.grad.zero_()\nbias.grad.zero_()"},
            {"type": "paragraph", "content": "In one-feature linear regression, the model is learning the slope and intercept of a line. Weight controls how strongly the input changes the prediction. Bias shifts the whole line upward or downward. Training is just repeated small corrections to those two values."},
            {"type": "code", "title": "Line intuition", "content": "pred = weight * x + bias\n# bigger weight -> steeper line\n# bigger bias   -> line shifts upward"},
            {"type": "paragraph", "content": "If you remember school algebra, this is the same idea as `y = mx + b`. Here `m` is the weight and `b` is the bias. PyTorch is just learning those values automatically from data instead of you choosing them by hand."},
            {"type": "paragraph", "content": "The residual is `preds - targets`. It tells you the signed error. Positive residual means the model predicted too high. Negative residual means the model predicted too low. Squaring the residual removes the sign and penalizes larger mistakes more heavily."},
            {"type": "code", "title": "Residual example", "content": "preds = torch.tensor([[8.0], [4.0]])\ntargets = torch.tensor([[5.0], [6.0]])\nresiduals = preds - targets\n# tensor([[ 3.0],\n#         [-2.0]])"},
            {"type": "paragraph", "content": "The loss is the number the optimizer cares about. A lower loss means the model predictions match the targets better overall. During training, you are not directly telling the model what the right weight is. You are telling it how wrong it currently is, and gradient descent uses that signal."},
            {"type": "code", "title": "Creating trainable parameters", "content": "weight = torch.randn(1, 1, requires_grad=True)\nbias = torch.zeros(1, requires_grad=True)"},
            {"type": "list", "title": "What changes during one training step", "items": ["The forward pass computes predictions.", "The loss compares predictions to targets.", "Backward computes gradients with respect to weight and bias.", "The update changes weight and bias slightly.", "The next forward pass uses the new parameter values."]},
            {"type": "paragraph", "content": "The gradient tells you direction, not the final answer. A positive gradient means increasing that parameter would increase the loss locally, so gradient descent moves the parameter downward. A negative gradient means increasing the parameter would reduce the loss locally, so gradient descent moves it upward."},
            {"type": "code", "title": "Why subtract the gradient", "content": "parameter = parameter - learning_rate * gradient"},
            {"type": "paragraph", "content": "That subtraction rule is why the method is called gradient descent. The gradient points uphill, toward increasing loss. Subtracting the gradient moves downhill, toward lower loss. The learning rate controls how big a step you take."},
            {"type": "paragraph", "content": "For mean squared error, the math strongly punishes large mistakes because errors are squared. If one prediction is off by 10 and another is off by 1, the first contributes 100 to the squared error while the second contributes only 1."},
            {"type": "math", "title": "MSE In Math Form", "content": "MSE = (1/n) Σᵢ (ŷᵢ - yᵢ)²"},
            {"type": "math", "title": "Gradient-Descent Sign Rule", "content": "∂L/∂w > 0  ⇒  increase in w raises L  ⇒  move w downward\n∂L/∂w < 0  ⇒  increase in w lowers L   ⇒  move w upward\n\nw ← w - η · ∂L/∂w"},
            {"type": "code", "title": "Worked example: one full regression step", "content": "x = torch.tensor([[1.0], [2.0]])\ny = torch.tensor([[3.0], [5.0]])\nweight = torch.tensor([[1.0]], requires_grad=True)\nbias = torch.tensor([0.0], requires_grad=True)\n\npreds = x @ weight + bias\nloss = ((preds - y) ** 2).mean()\nloss.backward()"},
            {"type": "paragraph", "content": "In that worked example, the predictions are too low, so the gradients should push the parameters in a direction that increases the model outputs. Looking at whether predictions are too high or too low is a useful sanity check before you even inspect the exact gradient values."},
            {"type": "callout", "title": "Common mistakes in manual regression", "content": "Wrong tensor shapes for `x @ weight`, forgetting `requires_grad=True`, forgetting to clear gradients, and updating parameters without `torch.no_grad()` are the most common mistakes."},
            {"type": "list", "title": "Recap checkpoint", "items": ["Can you explain what weight and bias do in a linear model?", "Can you compute residuals and MSE from predictions and targets?", "Can you explain why subtracting the gradient moves downhill?", "Can you describe one full manual training step in order?"]},
            {"type": "callout", "title": "Why MSE uses a mean", "content": "A mean loss stays on a similar scale even if the batch size changes. Without the mean, the loss would automatically grow when you use more examples in a batch."},
            {"type": "callout", "title": "How to read improvement", "content": "If the loss is going down across steps, the model is generally learning. If it explodes or becomes `nan`, the learning rate may be too high or the computation may be unstable."},
            {"type": "callout", "title": "Most common bug here", "content": "Forgetting `torch.no_grad()` during the parameter update creates a graph through the update itself. That usually causes confusing autograd behavior later."},
        ],
    },
    {
        "id": "03",
        "number": "03",
        "title": "Linear Regression With nn.Module",
        "lesson": "03_linear_regression_with_nn_module",
        "summary": "See the same regression problem expressed with nn.Module, DataLoader, and an optimizer.",
        "image": "05_perceptron.png",
        "script_path": "tutorials/03_linear_regression_with_nn_module.py",
        "pdf_path": "tutorials/pdfs/03_linear_regression_with_nn_module.pdf",
        "question_ids": ["q05_tiny_linear_forward", "q18_build_linear_layer", "q19_make_regression_loader", "q20_compute_mse_loss", "q21_run_training_step"],
        "previous_chapter": "02",
        "next_chapter": "04",
        "sections": [
            {"type": "paragraph", "content": "Nothing magical happens inside nn.Module. PyTorch just packages trainable tensors, the forward pass, and optimizer-friendly parameter access in a cleaner abstraction."},
            {"type": "code", "title": "Standard training pattern", "content": "preds = model(batch_x)\nloss = loss_fn(preds, batch_y)\noptimizer.zero_grad()\nloss.backward()\noptimizer.step()"},
            {"type": "paragraph", "content": "This chapter is the same learning problem as the previous one, but organized using PyTorch's standard abstractions. Instead of manually storing `weight` and `bias`, you define a module. Instead of manually stepping each tensor, you use an optimizer."},
            {"type": "list", "title": "What nn.Module gives you", "items": ["A place to define layers in `__init__`.", "A `forward()` method that describes the computation.", "Automatic parameter registration so optimizers can find trainable weights.", "Cleaner code once models get bigger than one formula."]},
            {"type": "code", "title": "Minimal module", "content": "class TinyLinearModel(nn.Module):\n    def __init__(self):\n        super().__init__()\n        self.linear = nn.Linear(1, 1)\n\n    def forward(self, x):\n        return self.linear(x)"},
            {"type": "paragraph", "content": "A module is really just a Python object with trainable tensors attached to it. Calling the module runs `forward()`. The optimizer then asks the module for its parameters and updates them after gradients are computed."},
            {"type": "list", "title": "How the pieces fit together", "items": ["The model maps inputs to predictions.", "The loss function scores those predictions.", "The optimizer updates model parameters.", "The dataloader keeps feeding fresh mini-batches into this loop."]},
            {"type": "paragraph", "content": "A `DataLoader` groups examples into batches. That matters because training usually happens on many examples at once, not one sample at a time. The loader also handles shuffling so the model does not always see data in exactly the same order."},
            {"type": "code", "title": "Batch training flow", "content": "for batch_x, batch_y in loader:\n    preds = model(batch_x)\n    loss = loss_fn(preds, batch_y)\n    optimizer.zero_grad()\n    loss.backward()\n    optimizer.step()"},
            {"type": "paragraph", "content": "Notice that the overall mathematical story did not change from the manual chapter. Only the code organization changed. The model still computes predictions, the loss still measures error, and gradient descent still updates parameters."},
            {"type": "paragraph", "content": "Notice how much shorter the training loop becomes once PyTorch owns the parameter bookkeeping. That is the main reason `nn.Module` is used everywhere. It lets you scale from one linear layer to deep networks without changing the overall training pattern."},
            {"type": "code", "title": "Tiny regression dataloader", "content": "dataset = TensorDataset(x, y)\nloader = DataLoader(dataset, batch_size=32, shuffle=True)"},
            {"type": "code", "title": "Parameter inspection", "content": "for name, param in model.named_parameters():\n    print(name, param.shape)"},
            {"type": "paragraph", "content": "An optimizer like SGD is basically a helper that performs the update rule for every trainable parameter in the model. Instead of writing separate update lines for each tensor, you call `optimizer.step()` and let PyTorch handle the loop over parameters."},
            {"type": "code", "title": "What optimizer.step() is conceptually doing", "content": "for parameter in model.parameters():\n    parameter -= learning_rate * parameter.grad"},
            {"type": "paragraph", "content": "Why call `optimizer.zero_grad()` before `backward()`? Because gradients accumulate by default in PyTorch. If you skip zeroing, the next backward pass adds new gradients on top of old ones, which is usually not what you want in a standard training loop."},
            {"type": "code", "title": "Worked example: module training step", "content": "model = nn.Linear(1, 1)\nloss_fn = nn.MSELoss()\noptimizer = torch.optim.SGD(model.parameters(), lr=0.1)\n\npreds = model(batch_x)\nloss = loss_fn(preds, batch_y)\noptimizer.zero_grad()\nloss.backward()\noptimizer.step()"},
            {"type": "paragraph", "content": "Even though the code is shorter here, the meaning is the same as in the manual chapter. The difference is mostly about abstraction and organization, not different mathematics."},
            {"type": "callout", "title": "Common mistakes with nn.Module training", "content": "Creating layers inside `forward()`, forgetting `optimizer.zero_grad()`, mismatching batch shapes, and confusing the model object with its output tensor are common beginner mistakes."},
            {"type": "list", "title": "Recap checkpoint", "items": ["Can you explain what `nn.Module` stores for you?", "Can you explain what `optimizer.step()` is conceptually doing?", "Can you explain why `DataLoader` is useful?", "Can you describe the normal forward/loss/backward/step loop?"]},
            {"type": "callout", "title": "Important training order", "content": "A safe default order is: forward, loss, zero_grad, backward, step. Many bugs in beginner training code come from getting that order wrong."},
            {"type": "callout", "title": "Mental model", "content": "Modules organize parameters. Loss functions score predictions. Optimizers update parameters using the gradients that autograd computed."},
            {"type": "callout", "title": "Why DataLoader matters", "content": "Once datasets get large, loading everything manually becomes messy. `DataLoader` standardizes batching, shuffling, and iteration so model code stays clean."},
            {"type": "callout", "title": "Beginner mistake", "content": "Do not create new layers inside `forward()`. Define them once in `__init__`. Otherwise the model creates fresh random weights every time it runs."},
        ],
    },
    {
        "id": "04",
        "number": "04",
        "title": "Logistic Regression From Scratch",
        "lesson": "04_logistic_regression_from_scratch",
        "summary": "Move from regression to binary classification with logits, sigmoid, and binary cross-entropy.",
        "image": "04_logistic_curve.png",
        "script_path": "tutorials/04_logistic_regression_from_scratch.py",
        "pdf_path": "tutorials/pdfs/04_logistic_regression_from_scratch.pdf",
        "question_ids": ["q06_logistic_probability", "q22_sigmoid_function", "q23_threshold_predictions", "q24_make_binary_labels", "q25_binary_cross_entropy"],
        "previous_chapter": "03",
        "next_chapter": "05",
        "sections": [
            {"type": "paragraph", "content": "Logistic regression still starts with a linear formula, but now you interpret the output as a probability by applying sigmoid to the raw logit."},
            {"type": "code", "title": "Probability path", "content": "logits = x @ weight + bias\nprobs = torch.sigmoid(logits)"},
            {"type": "callout", "title": "Important distinction", "content": "A logit is any real number. A probability must lie between 0 and 1."},
            {"type": "paragraph", "content": "Regression predicts continuous values like price or temperature. Logistic regression predicts the probability of one class, often written as 0 vs 1. The math starts similarly, but the interpretation is different."},
            {"type": "list", "title": "Classification pipeline", "items": ["Compute a linear score called a logit.", "Apply sigmoid to convert the logit to a probability.", "Compare that probability to the true label.", "Use binary cross-entropy to penalize wrong confident predictions."]},
            {"type": "code", "title": "Thresholding probabilities", "content": "probs = torch.sigmoid(logits)\npreds = (probs >= 0.5).float()"},
            {"type": "paragraph", "content": "Sigmoid takes any real number and squashes it into the range 0 to 1. Large positive logits become probabilities near 1. Large negative logits become probabilities near 0. A logit of 0 maps to probability 0.5, which sits right at the decision boundary."},
            {"type": "code", "title": "Reading logits", "content": "torch.sigmoid(torch.tensor([-4.0, 0.0, 4.0]))\n# tensor close to [0.018, 0.500, 0.982]"},
            {"type": "paragraph", "content": "That is why the sign of the logit matters so much. Positive logit pushes the prediction toward class 1. Negative logit pushes it toward class 0. The larger the magnitude, the more confident the model is."},
            {"type": "paragraph", "content": "Binary cross-entropy becomes very large when the model is confidently wrong. If the true label is 1 but the model predicts a probability close to 0, the loss should strongly punish that mistake."},
            {"type": "code", "title": "Manual BCE idea", "content": "preds = preds.clamp(1e-7, 1 - 1e-7)\nloss = -(targets * torch.log(preds) + (1 - targets) * torch.log(1 - preds)).mean()"},
            {"type": "paragraph", "content": "The BCE formula has two parts. One part is active when the label is 1 and asks the model to make `log(pred)` large, which means `pred` should be close to 1. The other part is active when the label is 0 and asks the model to make `log(1 - pred)` large, which means `pred` should be close to 0."},
            {"type": "math", "title": "BCE In Math Form", "content": "BCE = -[y log(p) + (1 - y) log(1 - p)]"},
            {"type": "list", "title": "How to read class outputs", "items": ["Probability near 0 means strong belief in class 0.", "Probability near 1 means strong belief in class 1.", "Probability near 0.5 means the model is uncertain.", "Thresholding converts probabilities into hard class decisions."]},
            {"type": "code", "title": "Making binary labels", "content": "scores = torch.tensor([-2.0, 0.3, 1.7])\nlabels = (scores > 0).float().unsqueeze(1)"},
            {"type": "paragraph", "content": "Classification labels are usually stored as 0 and 1. The model does not directly emit those labels during training. It emits probabilities, because probabilities provide a smoother learning signal for gradient-based optimization."},
            {"type": "paragraph", "content": "This matters for gradients too. A hard threshold like `(probs >= 0.5)` is fine for evaluation, but it is not the object you want inside the training loss. The smooth probability is what lets gradient-based learning work well."},
            {"type": "math", "title": "Sigmoid At Zero", "content": "σ(z) = 1 / (1 + e⁻ᶻ)\nσ(0) = 1 / (1 + e⁰)\n     = 1 / (1 + 1)\n     = 1/2 = 0.5"},
            {"type": "code", "title": "Worked example: logistic probability and threshold", "content": "logits = torch.tensor([[-2.0], [0.0], [2.0]])\nprobs = torch.sigmoid(logits)\npreds = (probs >= 0.5).float()"},
            {"type": "paragraph", "content": "That worked example shows the full interpretation chain: raw score -> probability -> hard class. During learning, the probability is the important smooth quantity. During reporting, the hard class is often what people want to see."},
            {"type": "callout", "title": "Common mistakes in manual logistic regression", "content": "Using hard thresholded predictions inside the training loss, forgetting that probabilities must lie in `[0, 1]`, and mixing up logits with probabilities are the most common mistakes."},
            {"type": "list", "title": "Recap checkpoint", "items": ["Can you explain what a logit is?", "Can you explain why sigmoid maps to the interval `[0, 1]`?", "Can you explain why BCE punishes confident wrong predictions strongly?", "Can you explain why thresholding is for evaluation, not for the training loss?"]},
            {"type": "callout", "title": "Math intuition", "content": "When the model is confident and correct, BCE becomes small. When the model is confident and wrong, BCE becomes large. That is exactly the behavior you want from a classification loss."},
            {"type": "callout", "title": "Why clamping matters", "content": "If a predicted probability becomes exactly 0 or 1, taking a log can cause numerical trouble. Clamping avoids `log(0)` in the manual formula."},
            {"type": "callout", "title": "Why probabilities help learning", "content": "A hard 0 or 1 class prediction throws away uncertainty. A probability like 0.62 tells you much more about how the model currently feels, which makes it more useful inside a differentiable loss."},
            {"type": "callout", "title": "Common confusion", "content": "A class prediction like 0 or 1 is not the same thing as a probability. The probability is the model's confidence before thresholding."},
        ],
    },
    {
        "id": "05",
        "number": "05",
        "title": "Logistic Regression With nn.Module",
        "lesson": "05_logistic_regression_with_nn_module",
        "summary": "Use nn.Linear and BCEWithLogitsLoss so PyTorch handles the standard binary-classification stack.",
        "image": "05_perceptron.png",
        "script_path": "tutorials/05_logistic_regression_with_nn_module.py",
        "pdf_path": "tutorials/pdfs/05_logistic_regression_with_nn_module.pdf",
        "question_ids": ["q07_logistic_module_forward", "q26_build_logistic_layer", "q27_logits_to_probs", "q28_make_bce_loss", "q29_predict_binary_classes"],
        "previous_chapter": "04",
        "next_chapter": None,
        "sections": [
            {"type": "paragraph", "content": "In PyTorch you usually return raw logits from forward() and let BCEWithLogitsLoss handle the stable sigmoid-plus-loss computation during training."},
            {"type": "list", "title": "What to remember", "items": ["forward() returns logits, not probabilities", "torch.sigmoid is for interpretation during evaluation", "labels should match the output shape"]},
            {"type": "paragraph", "content": "This chapter repeats the previous classification idea with PyTorch's standard building blocks. The key improvement is numerical stability. `BCEWithLogitsLoss` combines the sigmoid step and the BCE calculation in a way that is more stable than manually doing both during training."},
            {"type": "code", "title": "Standard model and loss", "content": "model = nn.Linear(2, 1)\nloss_fn = nn.BCEWithLogitsLoss()\nlogits = model(x)\nloss = loss_fn(logits, y)"},
            {"type": "paragraph", "content": "This is a good example of a common PyTorch design pattern: keep the model output simple and let the loss function handle the numerically tricky transformation. That is why many models return logits, not already-processed probabilities."},
            {"type": "paragraph", "content": "Notice the difference between training and evaluation. During training, the loss function wants logits. During evaluation, a human usually wants probabilities or class labels, so you apply `torch.sigmoid` yourself after the forward pass."},
            {"type": "code", "title": "Evaluation flow", "content": "logits = model(x)\nprobs = torch.sigmoid(logits)\npreds = (probs >= 0.5).float()"},
            {"type": "list", "title": "Why this pattern is preferred", "items": ["The model stays simple: it only returns logits.", "The loss function handles the numerically sensitive part.", "You can still turn logits into probabilities when you want to inspect predictions."]},
            {"type": "paragraph", "content": "Numerical stability sounds abstract, but the practical idea is simple: some formulas are mathematically correct yet fragile on a computer. `BCEWithLogitsLoss` uses a more stable internal form than manually doing `sigmoid` followed by `log`, especially for very large positive or negative logits."},
            {"type": "paragraph", "content": "In practice, this pattern scales from logistic regression to much larger neural networks. Even deep classifiers often return logits first, and the training loss is responsible for converting them into a stable objective."},
            {"type": "code", "title": "Logits to probabilities", "content": "logits = torch.tensor([[-1.0], [0.0], [1.0]])\nprobs = torch.sigmoid(logits)\npreds = (probs >= 0.5).float()"},
            {"type": "code", "title": "Typical training step", "content": "logits = model(batch_x)\nloss = loss_fn(logits, batch_y)\noptimizer.zero_grad()\nloss.backward()\noptimizer.step()"},
            {"type": "list", "title": "Train vs evaluate checklist", "items": ["Training: model returns logits.", "Training: use BCEWithLogitsLoss on those logits.", "Evaluation: apply sigmoid if you want probabilities.", "Evaluation: threshold probabilities if you want hard class predictions."]},
            {"type": "paragraph", "content": "A useful way to think about this chapter is that the model and the loss have a contract. The model promises to output logits. The loss promises to interpret those logits correctly during training. Breaking that contract is what causes the common double-sigmoid mistake."},
            {"type": "code", "title": "Correct separation of responsibilities", "content": "class Model(nn.Module):\n    def forward(self, x):\n        return self.linear(x)   # logits only\n\nloss = nn.BCEWithLogitsLoss()(logits, labels)"},
            {"type": "code", "title": "Worked example: stable classification training step", "content": "model = nn.Linear(2, 1)\nloss_fn = nn.BCEWithLogitsLoss()\noptimizer = torch.optim.SGD(model.parameters(), lr=0.1)\n\nlogits = model(batch_x)\nloss = loss_fn(logits, batch_y)\noptimizer.zero_grad()\nloss.backward()\noptimizer.step()"},
            {"type": "paragraph", "content": "This chapter is really about separating concerns cleanly. The model returns logits. The loss handles training-time stability. Evaluation code turns logits into probabilities and class labels only when needed."},
            {"type": "callout", "title": "Common mistakes with BCEWithLogitsLoss", "content": "Applying sigmoid inside `forward()`, passing labels with the wrong shape, and confusing evaluation-time probabilities with training-time logits are the most common mistakes."},
            {"type": "list", "title": "Recap checkpoint", "items": ["Can you explain why `BCEWithLogitsLoss` expects logits?", "Can you explain why applying sigmoid twice is wrong?", "Can you describe the difference between training-time outputs and evaluation-time outputs?", "Can you explain how logits become probabilities and then classes?"]},
            {"type": "callout", "title": "Gradient intuition here", "content": "Even though you are using higher-level building blocks, the same gradient logic still applies. Backward computes how each weight change would affect the classification loss, and the optimizer uses that information to update the weights."},
            {"type": "callout", "title": "Very common bug", "content": "Do not apply `sigmoid` inside `forward()` and then also use `BCEWithLogitsLoss`. That would effectively apply the sigmoid logic twice."},
            {"type": "callout", "title": "Why this chapter matters later", "content": "The same separation between raw model outputs and interpretation shows up again in later architectures. Learning it here makes more advanced models feel less mysterious."},
            {"type": "callout", "title": "Shape reminder", "content": "If the model output is shape `(batch, 1)`, your labels should usually also be shape `(batch, 1)`, not `(batch,)`."},
        ],
    },
    {
        "id": "06",
        "number": "06",
        "title": "Manual MLP From Scratch",
        "lesson": "06_manual_mlp_from_scratch",
        "summary": "Build a small neural network with raw parameter tensors, a hidden layer, ReLU, and cross-entropy so the forward pass stays fully visible.",
        "image": "05_perceptron.png",
        "script_path": "tutorials/06_manual_mlp_from_scratch.py",
        "pdf_path": "tutorials/pdfs/06_manual_mlp_from_scratch.pdf",
        "question_ids": [],
        "previous_chapter": "05",
        "next_chapter": "07",
        "sections": [
            {"type": "paragraph", "content": "This chapter is the bridge from linear models to real neural networks. You still manage raw tensors manually, but now the model has a hidden layer and a nonlinear activation, which gives it more expressive power than logistic regression."},
            {"type": "list", "title": "Network architecture", "items": ["Input has 2 features.", "First layer maps `2 -> 16`.", "ReLU adds nonlinearity.", "Second layer maps `16 -> 2` logits for class prediction."]},
            {"type": "code", "title": "Raw parameter tensors", "content": "w1 = (torch.randn(2, 16) * 0.5).requires_grad_()\nb1 = torch.zeros(16, requires_grad=True)\nw2 = (torch.randn(16, 2) * 0.5).requires_grad_()\nb2 = torch.zeros(2, requires_grad=True)"},
            {"type": "paragraph", "content": "Those parameter shapes tell the whole story. `w1` mixes the two input features into sixteen hidden features. `w2` then turns those hidden features into two output scores, one for each class. The biases broadcast across the batch automatically."},
            {"type": "code", "title": "Forward pass", "content": "hidden_pre_activation = x @ w1 + b1\nhidden = relu(hidden_pre_activation)\nlogits = hidden @ w2 + b2"},
            {"type": "list", "title": "Shape flow", "items": ["`x` has shape `(batch, 2)`.", "`x @ w1 + b1` becomes `(batch, 16)`.", "`relu(...)` keeps shape `(batch, 16)`.", "`hidden @ w2 + b2` becomes `(batch, 2)`."]},
            {"type": "paragraph", "content": "The hidden layer is what makes this model different from a linear classifier. Without a hidden nonlinearity, stacking linear operations would still collapse into one linear map. ReLU breaks that limitation and lets the model learn more flexible decision boundaries."},
            {"type": "math", "title": "ReLU", "content": "ReLU(z) = max(0, z)"},
            {"type": "code", "title": "Manual ReLU function", "content": "def relu(x):\n    return torch.clamp(x, min=0.0)"},
            {"type": "paragraph", "content": "The dataset is XOR-like: class 1 appears when the two coordinates have the same sign, and class 0 appears when their signs differ. That is exactly the kind of pattern a plain linear boundary struggles with, so it is a good toy problem for an MLP."},
            {"type": "code", "title": "Label rule", "content": "y = ((x[:, 0] * x[:, 1]) > 0).long()"},
            {"type": "paragraph", "content": "The model outputs two logits, not probabilities. One logit is the raw score for class 0 and the other is the raw score for class 1. `F.cross_entropy` expects those raw logits together with integer class labels."},
            {"type": "code", "title": "Loss and prediction", "content": "loss = F.cross_entropy(logits, y)\npreds = logits.argmax(dim=1)"},
            {"type": "paragraph", "content": "`argmax(dim=1)` picks the winning class index for each example. That is how you turn the two output scores into hard class predictions for accuracy reporting."},
            {"type": "math", "title": "Affine Layers In Math Form", "content": "h_pre = XW₁ + b₁\nh = ReLU(h_pre)\nlogits = hW₂ + b₂"},
            {"type": "paragraph", "content": "It is useful to separate the linear and nonlinear parts explicitly. `XW + b` is an affine transformation. By itself, it can only create linear decision boundaries. ReLU bends the computation into something more expressive because it changes the function depending on whether each hidden value is positive or negative."},
            {"type": "math", "title": "Why Linear Layers Alone Are Not Enough", "content": "If h = XW₁ + b₁ and logits = hW₂ + b₂,\nthen logits = (XW₁ + b₁)W₂ + b₂\n           = X(W₁W₂) + (b₁W₂ + b₂)\nwhich is still one affine map."},
            {"type": "paragraph", "content": "That identity is the main mathematical reason hidden activations matter. Two stacked linear layers without a nonlinearity do not create a fundamentally richer model. They just produce another single linear transformation. ReLU prevents that collapse."},
            {"type": "code", "title": "One example forward pass", "content": "x_one = torch.tensor([[0.5, -0.2]])\nhidden_pre = x_one @ w1 + b1\nhidden = relu(hidden_pre)\nlogits = hidden @ w2 + b2"},
            {"type": "paragraph", "content": "Looking at one example can make the network feel less abstract. The first matrix multiply mixes the two input coordinates into sixteen hidden numbers. ReLU then zeroes out the negative hidden values. The final matrix multiply converts those hidden features into two class scores."},
            {"type": "paragraph", "content": "You can think of each hidden unit as a learned detector. One hidden unit might become active for points in a certain region of the plane, while another responds to a different region. The output layer then combines those learned detectors to decide the class."},
            {"type": "math", "title": "Parameter Count", "content": "w₁: 2 × 16 = 32\nb₁: 16\nw₂: 16 × 2 = 32\nb₂: 2\nTotal parameters = 32 + 16 + 32 + 2 = 82"},
            {"type": "paragraph", "content": "Counting parameters is a good habit. It tells you roughly how much capacity the model has and helps you verify that you understand the architecture. Even this tiny MLP already has far more flexibility than logistic regression."},
            {"type": "paragraph", "content": "Cross-entropy can also be understood at a higher level: it rewards the model when the correct class logit becomes large relative to the other logits. You do not need to write the full softmax by hand in normal PyTorch code, but the interpretation matters."},
            {"type": "math", "title": "Cross-Entropy Intuition", "content": "For one example with true class y:\nsoftmax(logits)_k = exp(z_k) / Σ_j exp(z_j)\nloss = -log(softmax(logits)_y)"},
            {"type": "paragraph", "content": "If the correct class gets most of the score mass, the loss is small. If the wrong class dominates, the loss is large. This makes cross-entropy a natural fit for multiclass classification."},
            {"type": "code", "title": "Accuracy computation", "content": "preds = logits.argmax(dim=1)\nacc = (preds == y).float().mean().item()"},
            {"type": "paragraph", "content": "Accuracy is a different object from the loss. Accuracy asks whether the top-scoring class is right. Cross-entropy asks how strongly the model supported the correct class. A model can have the same accuracy with very different losses depending on confidence."},
            {"type": "paragraph", "content": "The update loop is still gradient descent. The only difference from earlier chapters is that there are now four trainable tensors instead of one or two. Autograd still computes gradients for every parameter, and the no-grad block still applies the update rule tensor by tensor."},
            {"type": "code", "title": "Manual update loop", "content": "loss.backward()\nwith torch.no_grad():\n    for param in params:\n        param -= learning_rate * param.grad\nfor param in params:\n    param.grad.zero_()"},
            {"type": "callout", "title": "A debugging habit for manual MLPs", "content": "Print `hidden_pre_activation.shape`, `hidden.shape`, and `logits.shape` early. Then inspect a few actual values. Shape checks catch structure bugs; value checks catch conceptual bugs like all-hidden-units being zero."},
            {"type": "callout", "title": "What this chapter proves", "content": "`nn.Module` is convenient, not magical. Underneath the abstraction, neural networks are still tensor multiplications, bias adds, activations, a loss, gradients, and parameter updates."},
            {"type": "callout", "title": "Common mistakes", "content": "Forgetting to zero each parameter's gradient, using one output logit instead of two for `cross_entropy`, and forgetting that ReLU changes values but not shape are the most common beginner mistakes here."},
            {"type": "list", "title": "Recap checkpoint", "items": ["Can you explain why a hidden layer helps on this dataset?", "Can you trace the shapes from input to logits?", "Can you explain why the outputs are logits and not probabilities?", "Can you describe the full manual forward/backward/update loop?"]},
        ],
    },
    {
        "id": "07",
        "number": "07",
        "title": "Basic Neural Network With nn.Module",
        "lesson": "07_basic_nn_mlp_with_nn_module",
        "summary": "Rebuild the small classifier using `nn.Sequential`, `DataLoader`, validation, and an optimizer so the standard PyTorch workflow feels concrete.",
        "image": "05_perceptron.png",
        "script_path": "tutorials/07_basic_nn_mlp_with_nn_module.py",
        "pdf_path": "tutorials/pdfs/07_basic_nn_mlp_with_nn_module.pdf",
        "question_ids": [],
        "previous_chapter": "06",
        "next_chapter": "08",
        "sections": [
            {"type": "paragraph", "content": "This chapter solves a similar nonlinear classification problem as chapter 06, but now it uses `nn.Module` and `nn.Sequential`. The model is cleaner to define, and PyTorch handles parameter registration automatically."},
            {"type": "code", "title": "Sequential MLP", "content": "self.net = nn.Sequential(\n    nn.Linear(2, 16),\n    nn.ReLU(),\n    nn.Linear(16, 16),\n    nn.ReLU(),\n    nn.Linear(16, 2),\n)"},
            {"type": "paragraph", "content": "This is not a different mathematical idea from the from-scratch version. It is the same pattern expressed with standard building blocks. Each `nn.Linear` still performs a matrix multiply plus bias, and each `nn.ReLU` still applies a nonlinearity elementwise."},
            {"type": "list", "title": "Shape flow through the network", "items": ["Input batch shape `(64, 2)`.", "After `Linear(2, 16)`: `(64, 16)`.", "After second hidden layer: still `(64, 16)`.", "After final layer: `(64, 2)` logits."]},
            {"type": "paragraph", "content": "The batch dimension stays the same through these layers because the model transforms each example independently. The feature dimension changes because each layer maps one feature space into another."},
            {"type": "math", "title": "Linear layer view", "content": "output = input @ weight.T + bias"},
            {"type": "paragraph", "content": "That formula is worth memorizing. It explains why `nn.Linear(in_features, out_features)` changes the last dimension from `in_features` to `out_features` while preserving the batch size."},
            {"type": "paragraph", "content": "The lesson uses `nn.CrossEntropyLoss()`, which expects raw logits of shape `(batch, num_classes)` and integer labels of shape `(batch,)`. That is why you should not apply softmax before the loss here."},
            {"type": "math", "title": "Cross-Entropy Shape Contract", "content": "logits shape = (batch, C)\nlabels shape = (batch,)\nwhere each label is an integer in {0, 1, ..., C-1}"},
            {"type": "paragraph", "content": "That shape contract matters because each row of logits represents one example's class scores. The label for that row is a single integer telling PyTorch which class index is correct. This is different from binary BCE-style losses, where labels often have shape `(batch, 1)` and the model returns one logit per example."},
            {"type": "code", "title": "Standard training step", "content": "logits = model(batch_x)\nloss = loss_fn(logits, batch_y)\noptimizer.zero_grad()\nloss.backward()\noptimizer.step()"},
            {"type": "paragraph", "content": "This five-line training pattern is one of the core rhythms of PyTorch. Once it becomes familiar, many new models feel like variations on the same loop rather than completely new systems."},
            {"type": "paragraph", "content": "A useful mental model is to divide the training step into three phases. First, the forward pass computes predictions and a loss. Second, `backward()` computes gradients with respect to every trainable parameter. Third, the optimizer uses those gradients to change the parameters."},
            {"type": "math", "title": "What SGD Is Doing Conceptually", "content": "θ ← θ - η ∇θ L"},
            {"type": "paragraph", "content": "Adam is used in the script instead of plain SGD, but the core idea is still gradient-based descent. Adam adapts step sizes using running estimates of gradient statistics, which often makes small neural nets train more smoothly."},
            {"type": "code", "title": "DataLoader setup", "content": "train_ds = TensorDataset(x[:split], y[:split])\ntrain_loader = DataLoader(train_ds, batch_size=64, shuffle=True)"},
            {"type": "paragraph", "content": "A `DataLoader` keeps the training loop clean by handling batching and shuffling for you. Shuffling matters because it reduces the risk that the model sees examples in a fixed, biased order every epoch."},
            {"type": "paragraph", "content": "Batching also changes the gradient signal. One example can produce a noisy gradient. A mini-batch averages information from many examples, so the update is usually more stable. This is one reason mini-batch training became the standard approach."},
            {"type": "math", "title": "Mini-Batch View", "content": "For batch size B,\nloss_batch = (1/B) Σ_i L_i"},
            {"type": "paragraph", "content": "Because the loss is averaged over the batch, the gradient is also effectively an average signal over those examples. That is why changing batch size can change optimization behavior, even when the model architecture stays the same."},
            {"type": "code", "title": "Validation pass", "content": "model.eval()\nwith torch.no_grad():\n    val_logits = model(val_x)\n    val_loss = loss_fn(val_logits, val_y).item()\n    val_acc = accuracy(val_logits, val_y)"},
            {"type": "paragraph", "content": "Validation exists to check whether the model generalizes beyond the batches it trained on. If training performance rises but validation stays weak, the model may be memorizing rather than learning a useful decision rule."},
            {"type": "paragraph", "content": "In this particular lesson the train/eval switch does not change activations because there is no dropout or batch normalization. But the habit is still important. If you wait until later to learn that distinction, bugs become much harder to diagnose."},
            {"type": "code", "title": "Inspecting model parameters", "content": "for name, param in model.named_parameters():\n    print(name, param.shape)"},
            {"type": "paragraph", "content": "This is one of the best ways to demystify `nn.Sequential`. You can inspect the actual weight and bias tensors, see their shapes, and confirm that the 'high-level' model still contains the same trainable objects as the manual version."},
            {"type": "math", "title": "Parameter Count Example", "content": "Layer 1: 2×16 + 16 = 48\nLayer 2: 16×16 + 16 = 272\nLayer 3: 16×2 + 2 = 34\nTotal = 48 + 272 + 34 = 354"},
            {"type": "paragraph", "content": "That count is much larger than the manual single-hidden-layer network in chapter 06 because this model has two hidden affine layers. More parameters can mean more expressive power, but they also make overfitting more possible if the dataset is small or noisy."},
            {"type": "callout", "title": "train() vs eval()", "content": "This small network has no dropout or batch normalization, so the practical effect is limited here. But building the habit now matters because larger models depend on correct train/eval mode."},
            {"type": "callout", "title": "Softmax is for interpretation, not this loss call", "content": "If you want to inspect class probabilities, apply softmax only for analysis or display. Do not pass softmaxed outputs into `CrossEntropyLoss`, because the loss already handles the needed internal transformation."},
            {"type": "callout", "title": "Common mistakes", "content": "Applying softmax before `CrossEntropyLoss`, forgetting `optimizer.zero_grad()`, and mixing up logits with predicted class ids are the most common beginner mistakes in this chapter."},
            {"type": "list", "title": "Recap checkpoint", "items": ["Can you explain what `nn.Sequential` is really wrapping?", "Can you trace the batch and feature dimensions through the network?", "Can you explain why `CrossEntropyLoss` wants logits?", "Can you explain the role of validation data?"]},
        ],
    },
    {
        "id": "08",
        "number": "08",
        "title": "CNN Basics",
        "lesson": "08_cnn_basics",
        "summary": "Learn image tensor format, convolutions, pooling, flattening, and how to read the shape flow inside a tiny CNN.",
        "image": "01_matrix_multiplication.png",
        "script_path": "tutorials/08_cnn_basics.py",
        "pdf_path": "tutorials/pdfs/08_cnn_basics.pdf",
        "question_ids": [],
        "previous_chapter": "07",
        "next_chapter": "09",
        "sections": [
            {"type": "paragraph", "content": "This chapter is mostly about shape intuition. CNNs become much easier once you can read `(batch, channels, height, width)` comfortably and predict how each layer changes those dimensions."},
            {"type": "code", "title": "Image batch format", "content": "batch = torch.randn(4, 1, 28, 28)\nprint(batch.shape)   # (4, 1, 28, 28)"},
            {"type": "list", "title": "Meaning of each dimension", "items": ["`4` images in the batch.", "`1` input channel because the image is grayscale.", "`28` height.", "`28` width."]},
            {"type": "paragraph", "content": "PyTorch image tensors usually follow `(N, C, H, W)`. That ordering is different from how beginners sometimes imagine images, so it is worth making automatic now."},
            {"type": "code", "title": "Feature extractor", "content": "self.features = nn.Sequential(\n    nn.Conv2d(1, 8, kernel_size=3, padding=1),\n    nn.ReLU(),\n    nn.MaxPool2d(2),\n    nn.Conv2d(8, 16, kernel_size=3, padding=1),\n    nn.ReLU(),\n    nn.MaxPool2d(2),\n)"},
            {"type": "paragraph", "content": "A convolution layer learns small filters that slide across local image regions. That is the central CNN idea: use locality instead of immediately flattening the whole image into a giant vector."},
            {"type": "math", "title": "Convolution Output Size Formula", "content": "output_size = floor((input + 2·padding - kernel_size) / stride) + 1"},
            {"type": "paragraph", "content": "That formula is worth learning because it lets you predict CNN shapes instead of guessing. In this chapter, `kernel_size=3`, `padding=1`, and the default `stride=1`, so the convolution preserves height and width: `(28 + 2 - 3) / 1 + 1 = 28`."},
            {"type": "code", "title": "First block shape flow", "content": "(4, 1, 28, 28)\n-> Conv2d(1, 8, kernel_size=3, padding=1) -> (4, 8, 28, 28)\n-> ReLU -> (4, 8, 28, 28)\n-> MaxPool2d(2) -> (4, 8, 14, 14)"},
            {"type": "paragraph", "content": "Padding keeps the height and width the same for the 3x3 convolution here, while max pooling halves the spatial size. Pooling does not usually change the number of channels. It changes height and width by summarizing local neighborhoods."},
            {"type": "math", "title": "Why Pooling Halves Spatial Size", "content": "With `MaxPool2d(2)` and stride 2:\n28 -> 14\n14 -> 7"},
            {"type": "paragraph", "content": "Max pooling with kernel size 2 and stride 2 breaks the image into non-overlapping 2x2 windows. Each window becomes one number: its maximum. That is why height and width are halved."},
            {"type": "code", "title": "Second block shape flow", "content": "(4, 8, 14, 14)\n-> Conv2d(8, 16, kernel_size=3, padding=1) -> (4, 16, 14, 14)\n-> ReLU -> (4, 16, 14, 14)\n-> MaxPool2d(2) -> (4, 16, 7, 7)"},
            {"type": "paragraph", "content": "This common pattern increases channels while reducing spatial size. Intuitively, later layers describe more kinds of learned features, but on increasingly compact feature maps."},
            {"type": "paragraph", "content": "You can think of each output channel as one learned detector map. Early channels may respond to simple local patterns like edges or corners. Later channels can represent more complex combinations of earlier features."},
            {"type": "math", "title": "Parameter Count For The First Convolution", "content": "Each filter has shape 1×3×3 = 9 weights.\nWith 8 output channels: 8×9 = 72 weights.\nPlus 8 bias values.\nTotal = 80 parameters."},
            {"type": "paragraph", "content": "This parameter sharing is one of the main reasons CNNs are efficient for images. A fully connected layer from 28x28 pixels into many hidden units would need far more parameters because it would not reuse the same local filter across positions."},
            {"type": "code", "title": "Classifier head", "content": "self.classifier = nn.Sequential(\n    nn.Flatten(),\n    nn.Linear(16 * 7 * 7, 32),\n    nn.ReLU(),\n    nn.Linear(32, 3),\n)"},
            {"type": "paragraph", "content": "Flattening converts each example from shape `(16, 7, 7)` into one long vector of length `16 * 7 * 7 = 784`. The batch dimension stays separate, so the classifier receives shape `(4, 784)` before the first linear layer."},
            {"type": "paragraph", "content": "That flatten size must match exactly. If you change the input image size, remove a pooling layer, or alter padding, the correct input size of the first linear layer usually changes too. This is one of the most common places beginners get shape errors."},
            {"type": "code", "title": "Printing shapes layer by layer", "content": "x = batch\nfor layer in model.features:\n    x = layer(x)\n    print(layer.__class__.__name__, x.shape)"},
            {"type": "code", "title": "Full output meaning", "content": "logits = model(batch)\nprint(logits.shape)   # (4, 3)"},
            {"type": "paragraph", "content": "The output shape `(4, 3)` means four examples, each with three class scores. Those are logits, not probabilities. A later loss or evaluation step would decide how to interpret them."},
            {"type": "paragraph", "content": "Another useful concept is the receptive field: how much of the original image can influence one later activation. As you stack convolutions and pooling layers, each later feature can summarize a larger region of the input image."},
            {"type": "callout", "title": "Convolution vs pooling", "content": "Convolution learns filters. Pooling does not usually learn weights; it summarizes existing activations. They play different roles even though both change the feature maps."},
            {"type": "callout", "title": "Why printing shapes matters", "content": "CNN bugs are often just shape bugs with new vocabulary. Printing the tensor shape after each layer is still one of the fastest debugging tools you have."},
            {"type": "callout", "title": "Common mistakes", "content": "Forgetting `(N, C, H, W)`, using the wrong flatten size after pooling, and confusing channels with spatial dimensions are the most common beginner errors here."},
            {"type": "list", "title": "Recap checkpoint", "items": ["Can you explain why the first convolution creates 8 output channels?", "Can you explain what max pooling changes and what it preserves?", "Can you compute the flatten size before the linear layer?", "Can you trace the full shape flow from image batch to logits?"]},
        ],
    },
    {
        "id": "09",
        "number": "09",
        "title": "Vision Classifier",
        "lesson": "09_vision_classifier",
        "summary": "Train a CNN end to end on generated image patterns and practice the full supervised vision pipeline: dataset, dataloader, model, train loop, and evaluation.",
        "image": "01_matrix_multiplication.png",
        "script_path": "tutorials/09_vision_classifier.py",
        "pdf_path": "tutorials/pdfs/09_vision_classifier.pdf",
        "question_ids": [],
        "previous_chapter": "08",
        "next_chapter": "10",
        "sections": [
            {"type": "paragraph", "content": "The previous chapter explained the anatomy of a CNN. This chapter shows the whole vision workflow around it: generating image data, batching it, training a model, and measuring accuracy on held-out examples."},
            {"type": "paragraph", "content": "The dataset is synthetic on purpose. Real image datasets add downloads, transforms, and file-handling complexity. Here the goal is to understand the learning pipeline itself first."},
            {"type": "list", "title": "Three toy classes", "items": ["Vertical line.", "Horizontal line.", "Diagonal line."]},
            {"type": "code", "title": "Generated image shape", "content": "image = generate_pattern(label)\nprint(image.shape)   # (1, 16, 16)"},
            {"type": "paragraph", "content": "Each image includes a channel dimension, so a batch from the `DataLoader` has shape `(batch, 1, 16, 16)`. That is the normal PyTorch image layout even when the image is only grayscale."},
            {"type": "code", "title": "Dataset item contract", "content": "def __getitem__(self, index):\n    return self.images[index], self.labels[index]"},
            {"type": "paragraph", "content": "That pair `(image, label)` is the basic supervised-learning interface. The model sees the image; the loss compares its prediction with the integer class label."},
            {"type": "paragraph", "content": "The dataset is balanced on purpose because the code cycles through the three labels evenly. That means random guessing is not helped by one class being much more common than the others, which makes accuracy easier to interpret."},
            {"type": "paragraph", "content": "Noise is added to the synthetic images so the task is not too brittle. Without noise, the model could get away with memorizing exact pixel positions instead of learning the underlying pattern structure."},
            {"type": "code", "title": "Pattern generation idea", "content": "if label == 0:\n    image[:, image_size // 2 - 1:image_size // 2 + 1] = 1.0\nelif label == 1:\n    image[image_size // 2 - 1:image_size // 2 + 1, :] = 1.0\nelse:\n    idx = torch.arange(image_size)\n    image[idx, idx] = 1.0"},
            {"type": "paragraph", "content": "Looking at the generator makes the task concrete. Class 0 means a vertical bright stripe, class 1 means a horizontal stripe, and class 2 means a diagonal stripe. That is exactly the kind of local pattern CNNs are good at detecting."},
            {"type": "code", "title": "Vision CNN", "content": "self.net = nn.Sequential(\n    nn.Conv2d(1, 8, kernel_size=3, padding=1),\n    nn.ReLU(),\n    nn.MaxPool2d(2),\n    nn.Conv2d(8, 16, kernel_size=3, padding=1),\n    nn.ReLU(),\n    nn.MaxPool2d(2),\n    nn.Flatten(),\n    nn.Linear(16 * 4 * 4, 32),\n    nn.ReLU(),\n    nn.Linear(32, NUM_CLASSES),\n)"},
            {"type": "code", "title": "Shape flow", "content": "(64, 1, 16, 16)\n-> (64, 8, 16, 16)\n-> (64, 8, 8, 8)\n-> (64, 16, 8, 8)\n-> (64, 16, 4, 4)\n-> (64, 256)\n-> (64, 32)\n-> (64, 3)"},
            {"type": "paragraph", "content": "The final output size is 3 because there are three classes. As in earlier multiclass chapters, the network returns raw logits and `nn.CrossEntropyLoss()` compares those logits against integer class ids."},
            {"type": "math", "title": "Cross-Entropy Again", "content": "For one image with true class y:\nloss = -log(softmax(logits)_y)"},
            {"type": "paragraph", "content": "This means the loss becomes small when the model gives the correct class the largest relative score. It becomes large when the model strongly prefers the wrong class. That matches what we want from a vision classifier."},
            {"type": "code", "title": "Training step", "content": "logits = model(images)\nloss = loss_fn(logits, labels)\noptimizer.zero_grad()\nloss.backward()\noptimizer.step()"},
            {"type": "paragraph", "content": "Notice that the train loop does not manually compute accuracy on every mini-batch before the gradient step. The main object used for learning is the differentiable loss. Accuracy is useful for monitoring, but it is not the quantity the optimizer directly minimizes."},
            {"type": "code", "title": "Evaluation step", "content": "with torch.no_grad():\n    logits = model(images)\n    preds = logits.argmax(dim=1)\n    correct += (preds == labels).sum().item()"},
            {"type": "paragraph", "content": "Evaluation uses `argmax(dim=1)` because each image gets one score per class. The class with the largest score is the predicted label."},
            {"type": "math", "title": "Accuracy Formula", "content": "accuracy = correct_predictions / total_predictions"},
            {"type": "paragraph", "content": "Train accuracy and test accuracy answer related but different questions. Train accuracy asks how well the model fits examples it has already seen. Test accuracy asks how well that learned rule transfers to unseen images."},
            {"type": "paragraph", "content": "The script reports both train accuracy and test accuracy. This matters because fitting the training data well is not enough; you want the model to perform well on unseen examples too."},
            {"type": "paragraph", "content": "In bigger projects, the same structure usually remains: a dataset object, a dataloader, a model, a loss, an optimizer, a training loop, and a validation or test loop. What changes is mostly scale and data complexity."},
            {"type": "callout", "title": "What this prepares you for", "content": "This toy pipeline has the same major pieces as real image classification work. Later you can swap in real datasets, transforms, normalization, and larger models without changing the basic training structure."},
            {"type": "callout", "title": "Why synthetic data is pedagogically useful", "content": "Because you already know exactly what the classes mean, you can focus on tensor shapes, losses, and evaluation rather than spending energy on downloading, cleaning, and understanding a real dataset."},
            {"type": "callout", "title": "Common mistakes", "content": "Forgetting the channel dimension, using the wrong flatten size after pooling, and treating logits as probabilities instead of class scores are the main beginner mistakes here."},
            {"type": "list", "title": "Recap checkpoint", "items": ["Can you explain why the dataset returns `(image, label)` pairs?", "Can you trace the shape flow through the CNN?", "Can you explain why the final layer has 3 outputs?", "Can you explain why test accuracy is tracked separately from train accuracy?"]},
        ],
    },
    {
        "id": "10",
        "number": "10",
        "title": "LSTM Sequence Classifier",
        "lesson": "10_lstm_sequence_classifier",
        "summary": "Learn sequence modeling with token ids, embeddings, LSTM hidden states, and a classifier built from the final sequence summary.",
        "image": "00_gradient_descent.png",
        "script_path": "tutorials/10_lstm_sequence_classifier.py",
        "pdf_path": "tutorials/pdfs/10_lstm_sequence_classifier.pdf",
        "question_ids": [],
        "previous_chapter": "09",
        "next_chapter": None,
        "sections": [
            {"type": "paragraph", "content": "This chapter introduces sequence modeling. Unlike images, sequence data has an order, and the model should care about that order. LSTMs are useful to study because they build a strong mental model for ordered data before you move on to transformers."},
            {"type": "list", "title": "Pipeline", "items": ["Integer token ids go into an embedding layer.", "Embeddings go into the LSTM.", "The LSTM produces sequence outputs and hidden states.", "A classifier uses the final hidden state to predict one class for the whole sequence."]},
            {"type": "code", "title": "Model definition", "content": "self.embedding = nn.Embedding(VOCAB_SIZE, 32)\nself.lstm = nn.LSTM(input_size=32, hidden_size=32, batch_first=True)\nself.classifier = nn.Linear(32, 2)"},
            {"type": "paragraph", "content": "The input starts as token ids of shape `(batch, seq_len)`. Those integers are not rich enough by themselves, so the embedding layer converts each token id into a learned dense vector."},
            {"type": "code", "title": "Embedding shape change", "content": "tokens shape: (64, 10)\nembedded = self.embedding(tokens)\nembedded shape: (64, 10, 32)"},
            {"type": "paragraph", "content": "An embedding layer is like a learnable lookup table. Every token id maps to one trainable vector. Similar tokens can eventually get similar embeddings if the training problem encourages that."},
            {"type": "math", "title": "Embedding Table Shape", "content": "Embedding matrix shape = (vocab_size, embedding_dim)\nHere: (15, 32)"},
            {"type": "paragraph", "content": "`batch_first=True` means PyTorch will use shapes `(batch, seq_len, features)` instead of `(seq_len, batch, features)`. That is often easier for beginners to read."},
            {"type": "code", "title": "LSTM outputs", "content": "outputs, (hidden_state, cell_state) = self.lstm(embedded)"},
            {"type": "list", "title": "Returned tensors", "items": ["`outputs` shape `(batch, seq_len, hidden_size)` gives one output per time step.", "`hidden_state` shape `(num_layers, batch, hidden_size)` stores the final hidden state for each layer.", "`cell_state` has the same shape as `hidden_state` and represents the LSTM's internal memory state."]},
            {"type": "paragraph", "content": "Many beginners get stuck because three different tensors come back from the LSTM call. The easiest way to stay clear is to ask: do I want a representation for every position, or one summary for the whole sequence? `outputs` is position-by-position. `hidden_state[-1]` is a whole-sequence summary."},
            {"type": "math", "title": "LSTM Gate Sketch", "content": "f_t = σ(W_f [h_{t-1}, x_t] + b_f)\ni_t = σ(W_i [h_{t-1}, x_t] + b_i)\no_t = σ(W_o [h_{t-1}, x_t] + b_o)\n\\tilde{c}_t = tanh(W_c [h_{t-1}, x_t] + b_c)\nc_t = f_t ⊙ c_{t-1} + i_t ⊙ \\tilde{c}_t\nh_t = o_t ⊙ tanh(c_t)"},
            {"type": "paragraph", "content": "You do not need to memorize every gate equation immediately, but the structure is worth seeing once. The forget gate decides what old information to keep, the input gate decides what new information to write, and the output gate decides what part of the memory becomes the visible hidden state."},
            {"type": "paragraph", "content": "In this one-layer LSTM, `hidden_state[-1]` is the last layer's final hidden state, so it has shape `(batch, hidden_size)`. That makes it a convenient summary vector for sequence classification."},
            {"type": "code", "title": "Sequence summary for classification", "content": "final_hidden = hidden_state[-1]\nlogits = self.classifier(final_hidden)"},
            {"type": "paragraph", "content": "The classifier then does exactly the same kind of thing you have seen before in feedforward networks: it maps one feature vector per example into class logits. The new part is how that feature vector was created from an ordered sequence."},
            {"type": "paragraph", "content": "The toy labeling rule depends on comparing the later half of the sequence with the earlier half. That means sequence order matters. If you shuffle the same token values into a different order, the label can change."},
            {"type": "code", "title": "Toy label rule", "content": "first_half = tokens[:, : SEQ_LEN // 2].float().mean(dim=1)\nsecond_half = tokens[:, SEQ_LEN // 2 :].float().mean(dim=1)\nlabels = (second_half > first_half).long()"},
            {"type": "math", "title": "Label Rule In Math Form", "content": "label = 1 if mean(second half) > mean(first half)\nlabel = 0 otherwise"},
            {"type": "paragraph", "content": "That kind of task is exactly what sequence models are for: learn from values across time or position, not just from an unordered bag of numbers."},
            {"type": "paragraph", "content": "Notice that a plain average over all tokens would throw away the very information that defines the label here. The model needs some way to preserve the distinction between earlier and later positions, and the recurrent state gives it that mechanism."},
            {"type": "code", "title": "Validation prediction", "content": "val_logits = model(val_x)\nval_preds = val_logits.argmax(dim=1)\nval_acc = (val_preds == val_y).float().mean().item()"},
            {"type": "paragraph", "content": "As in the multiclass MLP and CNN chapters, the logits are turned into class predictions with `argmax(dim=1)`. The only major difference is that those logits now summarize a whole sequence rather than an image or tabular point."},
            {"type": "callout", "title": "outputs vs hidden_state", "content": "`outputs` gives one vector per time step. `hidden_state` gives the final summary state per layer. Beginners often mix them up, so keep the distinction explicit."},
            {"type": "callout", "title": "LSTM intuition", "content": "Think of the model as reading tokens one by one, updating an internal memory, and then using its final memory summary to make a class decision."},
            {"type": "callout", "title": "Why this chapter matters", "content": "LSTMs are not the newest dominant sequence model, but they teach durable ideas: embeddings, temporal order, hidden memory, and reducing a whole sequence to one vector for classification."},
            {"type": "list", "title": "Recap checkpoint", "items": ["Can you explain why token ids need an embedding layer?", "Can you explain the difference between `outputs` and `hidden_state`?", "Can you explain why `hidden_state[-1]` works as a sequence summary?", "Can you explain why order matters in this toy task?"]},
        ],
    },
]


CHAPTERS_BY_ID = {chapter["id"]: chapter for chapter in CHAPTERS}


def public_chapter_summaries() -> list[dict[str, object]]:
    return [
        {
            "id": chapter["id"],
            "number": chapter["number"],
            "title": chapter["title"],
            "lesson": chapter["lesson"],
            "summary": chapter["summary"],
            "image": chapter["image"],
            "question_count": len(chapter["question_ids"]),
        }
        for chapter in CHAPTERS
    ]


def get_chapter(chapter_id: str) -> dict[str, object] | None:
    chapter = CHAPTERS_BY_ID.get(chapter_id)
    if chapter is None:
        return None
    return deepcopy(chapter)
